### ISSUE TITLE
ISSUE: Error in logs

### ISSUE THREAD

**Issue by jdc0730** [FutureTense/keymaster#103]
**Describe the bug**
I am getting the following error in the logs:

Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:489
Integration: Binary sensor (documentation, issues)
First occurred: 12:40:29 PM (2 occurrences)
Last logged: 12:40:29 PM

Platform keymaster does not generate unique IDs. ID keymaster_zwave_network_ready already exists - ignoring binary_sensor.keymaster_zwave_network_ready

**Note that I have three locks set up so I would guess it is trying to create the binary_sensor for each lock and throwing the two errors.**

**Environment (please complete the following information):**

- OS: Docker
- Type of device: Synology
- Home Assistant version: 2012.2.3
- Hassio/Docker/Core? Docker
- Component version: 0.23

**Logs**
See above

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Thank you for reporting, we'll have a look.

**Comment by raman325** [comment]
doh, I did not consider multiple config entries. Thanks for finding this, should be able to push a fix tonight

**Comment by jdc0730** [comment]
I am still seeing this error message in the logs. Running 0.25.

**Comment by raman325** [comment]
~~do you have multiple locks?~~ Just realized you are the original poster.

**Comment by raman325** [comment]
@jdc0730 I may have a potential fix, but before I push another release, I'd like to verify it works. Can you clone down the `fix_network_ready` branch from my fork and copy it into your custom_components folder and see if it resolves the issue?

https://github.com/raman325/keymaster/tree/fix_network_ready (make sure you checkout the right branch before you copy it over)

**Comment by jdc0730** [comment]
@raman325 Looks like the branch has fixed the problem. I am not seeing the message in the logs anymore. I disabled, then enabled, a code and it updated appropriately. From what I can tell, everything appears to be working correctly. Thanks for the fix.

**Comment by raman325** [comment]
Thanks for confirming I’ll push out a new release shortly
