### ISSUE TITLE
zwave_js and ozw need clear lock code workaround of setting a random PIN

### ISSUE THREAD

**Issue by raman325** [FutureTense/keymaster#136]
As an aside, it was mentioned the random code instead of clearing was a workaround for the deprecated zwave integration.  According to my lock documentation, codes can only be cleared by overwriting with a different code.  How would that work with zwavejs?

> Deleting User Codes
In order to delete a user code, you must override the code by adding a different user code in the same position. For example, if
you want to delete the third code, add a different user code in position three.
If you cannot remember the user code position, you may wish to perform a factory reset to delete all codes associated with
the lock. See section “G.”
http://www.weiserlock.com/PDFs/instructions/Electronics/SmartCode_5_Installation_and_User_Guide_English.pdf (Section D-d)

_Originally posted by @thayerfox in https://github.com/FutureTense/keymaster/issues/121#issuecomment-800770247_

**Comment by firstof9** [comment]
My Kwikset also states this in the manual, yet the codes clear. I have yet to find a lock that will not clear it's code in `ozw` or `zwavejs`.

**Comment by raman325** [comment]
that's good to know. @thayerfox can you test this and report back? I'd prefer not to add more workarounds if we don't have to 🙂

**Comment by smiller171** [comment]
Unfortunately my older Yale Real Living YRD220 doesn't seem to want to clear
