### ISSUE TITLE
Lock Pin code not updating, and not connecting.

### ISSUE THREAD

**Issue by quadhammer** [FutureTense/keymaster#138]
Hello there, I'm having trouble getting my lock, an  Assa Abloy Yale Key Free Touchscreen Deadbolt (YRD446) to connect, or rather update the interface with the new code.

Here is an example of me sending 5455 to code spot 2, and it gets updated on the badge as you can see from the screenshot, but it just says connecting perpetually, and never updates.

I have the allow_automations boolean (input_boolean.allow_automation_execution) switched on when then the  Z-Wave (deprecated) network comes online.

If I go to the lock afterwards, 5455 works, so the command is getting through.

https://imgur.com/a/3l5SqMk

![2021-03-20 (5)](https://user-images.githubusercontent.com/20377571/111861455-07936080-899a-11eb-8b43-1403b28950e1.png)
![a2021-03-20 (5)](https://user-images.githubusercontent.com/20377571/111861457-0a8e5100-899a-11eb-8210-87f29fe56496.png)
![2021-03-20 (6)](https://user-images.githubusercontent.com/20377571/111861456-082bf700-899a-11eb-9f90-e2cc50ba0d48.png)

```
2021-03-20 15:52:29 DEBUG (MainThread) [custom_components.keymaster] Add Code service: <ServiceCall keymaster.add_code (c:e2f0f9bfb164d56292484fdafd4521ec): entity_id=lock.office_doorlock_locked_office_doorlock, code_slot=2, usercode=5455>
2021-03-20 15:52:29 DEBUG (MainThread) [custom_components.keymaster.services] Attempting to call set_usercode...
2021-03-20 15:52:32 DEBUG (SyncWorker_0) [custom_components.keymaster] DEBUG: Code slot 255 value: 250
2021-03-20 15:52:32 DEBUG (SyncWorker_0) [custom_components.keymaster] DEBUG: Code slot 254 value: False
2021-03-20 15:52:32 DEBUG (SyncWorker_0) [custom_components.keymaster] DEBUG: Code slot 0 value: 
2021-03-20 15:52:32 DEBUG (SyncWorker_0) [custom_components.keymaster] DEBUG: Code slot 1 value: 4578
2021-03-20 15:52:32 DEBUG (SyncWorker_0) [custom_components.keymaster] DEBUG: Utilizing Zwave clear_usercode work around code.
2021-03-20 15:52:32 DEBUG (SyncWorker_0) [custom_components.keymaster] DEBUG: Code slot 2 value: 5872





2021-03-20 15:52:37 DEBUG (SyncWorker_12) [custom_components.keymaster] DEBUG: Code slot 2 value: 5872

2021-03-20 15:52:42 DEBUG (SyncWorker_13) [custom_components.keymaster] DEBUG: Code slot 2 value: 5872

2021-03-20 15:52:47 DEBUG (SyncWorker_14) [custom_components.keymaster] DEBUG: Code slot 2 value: 5872

2021-03-20 15:52:52 DEBUG (SyncWorker_8) [custom_components.keymaster] DEBUG: Code slot 2 value: 5872

2021-03-20 15:52:57 DEBUG (MainThread) [custom_components.keymaster] Finished fetching keymaster data in 0.011 seconds
```

I'm not sure what the 3 assa three sensors are,or whether I should be using them in the configurations set up? They just appeared after refreshing the node one time.
eg. sensor.assa_abloy_yale_key_free_touchscreen_deadbolt_yrd446
![e2021-03-20 (5)](https://user-images.githubusercontent.com/20377571/111861454-05c99d00-899a-11eb-8b93-8e32ace5087e.png)

Any idea what I might be doing wrong, please?

**Comment by firstof9** [comment]
**Environment (please complete the following information):**

- OS: [e.g. HassOS/Raspbian/CentOS]
- Type of device: [e.g. RPi3/NUC/Synology]
- Home Assistant version: [e.g. 0.105.5]
- Hassio/Docker/Core?
- Component version: [e.g. 0.1.2]

**Comment by quadhammer** [comment]
## System Health

version | core-2021.3.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.99
arch | x86_64
timezone | Australia/Brisbane

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4682
Installed Version | 1.11.3
Stage | running
Available Repositories | 758
Installed Repositories | 26

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Hass.io</summary>

host_os | Home Assistant OS 5.12
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.6
docker_version | 19.03.13
disk_total | 30.8 GB
disk_used | 22.2 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.1), Mosquitto broker (5.1.1), Duck DNS (1.12.5), Node-RED (8.2.0), Dropbox Sync (1.3.0), ESPHome (1.16.2), Zigbee2mqtt (1.18.1-1), WireGuard (0.5.0), AdGuard Home (4.0.0), File editor (5.2.0), Network UPS Tools (0.6.2), Let's Encrypt (4.11.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 19
views | 37
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>


Windows 10 on a PC running Oracle Virtual Box 6.1
![2021-03-21](https://user-images.githubusercontent.com/20377571/111889940-ae2a4080-8a30-11eb-8468-396df8ca1cfc.png)

I can't see where the Keymaster version is, but I installed from HACS yesterday.  Sorry if I've missed the relevant bits, just let me know how to help.

**Comment by firstof9** [comment]
Does it clear if you untick `Enabled`?

**Comment by raman325** [comment]
You can see in the logs that the code we see set on the lock is 5872 and your desired pin is 5455 hence the reason the pin never shows as synchronized. Try disabling it as @firstof9 suggested, verify that the logs show the slot is clear, then try enabling it again

**Comment by quadhammer** [comment]
> Does it clear if you untick `Enabled`?

Yes, it goes back to disconnected.

> You can see in the logs that the code we see set on the lock is 5872 and your desired pin is 5455 hence the reason the pin never shows as synchronized. Try disabling it as @firstof9 suggested, verify that the logs show the slot is clear, then try enabling it again

I think I have had some success, by not only clicking 'reset code slot', but then 'Enabled' afterward.  I had assumed that simply clicking reset code slot would do both, but that doesn't seem to be the case.  

It doesn't clear the slot in the logs, but looks like it assigns a random number, which after accepts the new code.

As an aside:
"Select the service logger.set_level in data enter custom_components.keymaster: debug and press Call Service. Your log will now start showing debug data in the Home Assistant log."

Enabling this killed my home assistant instance after a pretty short time, and each action seems to be reported about five times, with the 255 codes.  Perhaps it might be worth noting, or supplying instructions to stop the logging afterwards.

Cheers!

**Comment by quadhammer** [comment]
Aarg, it's stuck on connecting again.  I was getting a duplicate code error on slot 2, despite it being disabled.  I don't think the clear slot is working, but I will post logs when I can have the network crash from turning logging on.

**Comment by firstof9** [comment]
All this headache can be avoided by migrating to `zwavejs`.

**Comment by raman325** [comment]
> All this headache can be avoided by migrating to `zwavejs`.

agreed.

@quadhammer can you try calling the service directly? Call `zwave.set_usercode` and manually set the slot and see if it works. If it doesn't, then it's an issue between the `zwave` integration and your lock, not `keymaster`. I ran into this issue often with both `zwave` and `ozw` and it forced me to re-pair my lock to resolve it. Moving to `zwave_js` eliminated the problem entirely

**Comment by maggar** [comment]
As an aside, I had the same problem with a kwikset lock that I migrated over to zwave_js from smartthings.  Turns out the lock still had codes in it, and until I set the codes to be the same in lovelace page as they were in the lock (same slots) they would not sync (would be in perpetual connecting/disconnecting state).  I found the matching codes by looking at the logs.

**Comment by quadhammer** [comment]
>  Turns out the lock still had codes in it, and until I set the codes to be the same in lovelace page as they were in the lock (same slots) they would not sync (would be in perpetual connecting/disconnecting state). I found the matching codes by looking at the logs.

Thanks, mate.  That was definitely one of the problems!  I've also migrated to zwavejs, so hopefully that will help too.

Thanks again for the Keymaster integration too.
