### ISSUE TITLE
ISSUE: Child locks not working

### ISSUE THREAD

**Issue by maggar** [FutureTense/keymaster#140]
Child locks functionality is not working.  Folder for lock does not get created when specifying a child lock file

**Environment (please complete the following information):**

Version | core-2021.3.4
-- | --
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
Virtual Environment | false
Python Version | 3.8.7
Operating System Family | Linux
Operating System Version | 5.4.99
CPU Architecture | x86_64

**Logs**
<details><summary>Trace as follows:</summary>

```log

File “/config/custom_components/keymaster/init.py”, line 418, in update_listener
     primary_lock, child_locks = await generate_keymaster_locks(hass, config_entry)
File “/config/custom_components/keymaster/helpers.py”, line 129, in generate_keymaster_locks
     child_locks = [
File “/config/custom_components/keymaster/helpers.py”, line 130, in
     KeymasterLock(
TypeError: init() missing 1 required positional argument: ‘door_sensor_entity_id’

2021-03-26 17:56:11 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Front Door for keymaster
Traceback (most recent call last):
File “/usr/src/homeassistant/homeassistant/config_entries.py”, line 248, in async_setup
     result = await component.async_setup_entry(hass, self) # type: ignore
File “/config/custom_components/keymaster/init.py”, line 166, in async_setup_entry
     primary_lock, child_locks = await generate_keymaster_locks(hass, config_entry)
File “/config/custom_components/keymaster/helpers.py”, line 129, in generate_keymaster_locks
     child_locks = [
File “/config/custom_components/keymaster/helpers.py”, line 130, in
     KeymasterLock(
TypeError: init() missing 1 required positional argument: ‘door_sensor_entity_id’

2021-03-26 17:59:40 ERROR (SyncWorker_8) [custom_components.keymaster.config_flow] The child locks file (/config/child_locks) does not exist

2021-03-26 17:59:49 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved

```
</details>

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by raman325** [comment]
As of now we don't generate templates for child locks. This feature is only partially built out. BTW, the errors you are seeing are on your end. You need to specify a `door_sensor_entity_id` (it can be `sensor.fake` if you don't have one) and the locks file needs to exist

**Comment by maggar** [comment]
I'm getting an error when I specify this value

Child locks file data is invalid: extra keys not allowed @ data['deck_north_door']['door_sensor_entity_id']

[Image]




Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by raman325** [comment]
ah this may be a bug, will look into it, thanks

**Comment by raman325** [comment]
This will be fixed in the next release, fixed in https://github.com/FutureTense/keymaster/pull/147
