### ISSUE TITLE
[Feature Request] Auto-relock

### ISSUE THREAD

**Issue by maggar** [FutureTense/keymaster#141]
Coming from Smartthings, the lock manager I was using had an option to specify a timeout period to relock the door if it was left unlocked

**Describe the solution you'd like**
In the config for the door (part of the integration), a timeout in minutes for door relock.  Door should only relock if the associated door sensor is closed.

**Describe alternatives you've considered**
Building an automation for each lock, which is ugly (multiple automations).  I'll probably end up doing this anyway because I need to the doors to relock before you'll have a chance to implement, else we might get robbed... :-)

**Additional context**

**Comment by firstof9** [comment]
Technically this is out of the scope of the integration, but maybe worth adding in.

@FutureTense @raman325 your thoughts?

**Comment by raman325** [comment]
My opinion is that this is a simple enough automation that I'm not sure what value we add by pulling it into keymaster. To me, making this work generically would be more work than would be required to just add an automation for it. This way you can also have other conditions stop the auto-lock, like presence detection and such

**Comment by FutureTense** [comment]
I have a fairly solid auto lock feature I use on my locks.  I’ll look at its feasibility if integration

**Comment by emteedubs** [comment]
I see the autolock functionality was included in the latest release. Amazing job! I was wondering if we could have an option in the configuration to disable autolock functionality such that the templates generated do not include them. Reason being, I already run my own autolock automations and they also incorporate checks of if my door is still open before enabling the re-lock.  So I'd like the ability to keep using my own autolock with the Keymaster integration but without added bloat of additional unused entities created from the integration.

**Comment by raman325** [comment]
I agree that making keymaster more modular would be pretty nice. I know a lot of people don't use the scheduling feature as an example. I will transfer that suggestion over to a new issue for tracking, but let's mark this one as complete
