### ISSUE TITLE
ISSUE: Error using child locks with Yale YRD225 and zwave-js

### ISSUE THREAD

**Issue by lox** [FutureTense/keymaster#143]
**Describe the bug**
Can't configure child locks with Yale YRD226 and zwave-js. When I set the child-locks path to `child-locks.yaml` I get an error `missing 1 required positional argument: 'door_sensor_entity_id`.

I've tried adding `door_sensor_entity_id` as a key in the yaml, but I get a validation error about it not being allowed. 

**Environment (please complete the following information):**

- OS: Debian 10
- Type of device: NUC
- Home Assistant version: core-2021.3.4
- Hassio: supervisor-2021.03.6
- Component version: v0.0.28

**Logs**
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/keymaster/__init__.py", line 418, in update_listener
    primary_lock, child_locks = await generate_keymaster_locks(hass, config_entry)
  File "/config/custom_components/keymaster/helpers.py", line 129, in generate_keymaster_locks
    child_locks = [
  File "/config/custom_components/keymaster/helpers.py", line 130, in <listcomp>
    KeymasterLock(
TypeError: __init__() missing 1 required positional argument: 'door_sensor_entity_id'
```

**Screenshots**

**Additional context**

config/child-locks.yaml
```
side_door:
  lock_entity_id: lock.side_door_lock
```

**Comment by raman325** [comment]
this will be fixed in the next release, fixed in https://github.com/FutureTense/keymaster/pull/147
