### ISSUE TITLE
ISSUE: YALE YRD110 Locks not being reported correctly

### ISSUE THREAD

**Issue by PrayerfulDrop** [FutureTense/keymaster#145]
**Describe the bug**
keymaster_lock_state_changed is not reporting the lock actions correctly for Yale YRD100 locks.  The zwave_js_event is showing correctly.  The label is showing the correct details in the zwave_js_event but the keymaster_lock_state_changed is not showing the same results.

**Environment (please complete the following information):**

- OS: HassOS
- Type of device: NUC
- Home Assistant version: 2021.3.4
- Hassio/Docker/Core? core-2021.3.4
- Hassio Supervisor: supervisor-2021.03.6
- Component version: 
   - supervisor - zwaveJS2MQTT 0.9.0 
   - zwavejs2mqtt: 3.0.1
   - zwave-js: 7.0.0

**Logs**
<details><summary>zwave_js_events:</summary>

```json
{
    "event_type": "zwave_js_event",
    "data": {
        "type": "notification",
        "domain": "zwave_js",
        "node_id": 63,
        "home_id": 4172338759,
        "device_id": "bedc99ab52b31dc30915eb5ce6e18d2f",
        "label": "RF lock operation",
        "parameters": {}
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-31T20:01:13.351540+00:00",
    "context": {
        "id": "6bc8c0be661e2290929075f239131589",
        "parent_id": null,
        "user_id": null
    }
}
Event 3 fired 2:58 PM:
{
    "event_type": "zwave_js_event",
    "data": {
        "type": "notification",
        "domain": "zwave_js",
        "node_id": 63,
        "home_id": 4172338759,
        "device_id": "bedc99ab52b31dc30915eb5ce6e18d2f",
        "label": "Keypad unlock operation",
        "parameters": {}
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-31T19:58:53.500648+00:00",
    "context": {
        "id": "fe98e38617eef0de785ff341b6fc289c",
        "parent_id": null,
        "user_id": null
    }
}
Event 2 fired 2:58 PM:
{
    "event_type": "zwave_js_event",
    "data": {
        "type": "notification",
        "domain": "zwave_js",
        "node_id": 63,
        "home_id": 4172338759,
        "device_id": "bedc99ab52b31dc30915eb5ce6e18d2f",
        "label": "Manual lock operation",
        "parameters": {}
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-31T19:58:52.473158+00:00",
    "context": {
        "id": "c643ea51d90cbb8a9553f95d6a6694d3",
        "parent_id": null,
        "user_id": null
    }
}
```
</details>

<details><summary>keymaster_lock_state_changed</summary>

```json
Event 1 fired 2:57 PM:

keymaster_lock_state_changed:
{
"event_type": "keymaster_lock_state_changed",
"data": {
"notification_source": "entity_state",
"lockname": "garagedoor",
"entity_id": "lock.garage_door",
"state": "locked",
"action_code": 130,
"action_text": "Unknown Alarm Type Value",
"code_slot": 1,
"code_slot_name": "Aaron"
},
"origin": "LOCAL",
"time_fired": "2021-03-30T22:04:43.730096+00:00",
"context": {
"id": "fcc515f6beb3467940f5e77aa4874aff",
"parent_id": null,
"user_id": null
}
}
```
</details>

**Comment by raman325** [comment]
Do you have a alarm level and alarm type defined in your `keymaster` config entry? If so, try switching them to `binary_sensor.fake` and see if that resolves the issue. This is likely due to the changes in `zwave-js 7.0.0` to always send lock/unlock events as notification events instead of entity updates. You can use one method (events) or the other (entities) but you can't use both 🙂

**Comment by PrayerfulDrop** [comment]
Here are my current settings:

![image](https://user-images.githubusercontent.com/999665/113206275-e00f8400-9234-11eb-9eb3-560bf005aa5c.png)

Now I am seeing the correct action type but now have lost the code_slot and code_slot_name.

Event 1 fired 3:20 PM:
{
    "event_type": "keymaster_lock_state_changed",
    "data": {
        "notification_source": "event",
        "lockname": "frontdoor",
        "entity_id": "lock.front_door",
        "state": "unlocked",
        "action_text": "Keypad unlock operation",
        "code_slot": 0,
        "code_slot_name": ""
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-31T20:20:18.192702+00:00",
    "context": {
        "id": "51c1313cb1ff5f620a76e8708a2c2f18",
        "parent_id": null,
        "user_id": null
    }
}
Event 0 fired 3:20 PM:
{
    "event_type": "keymaster_lock_state_changed",
    "data": {
        "notification_source": "event",
        "lockname": "frontdoor",
        "entity_id": "lock.front_door",
        "state": "locked",
        "action_text": "Manual lock operation",
        "code_slot": 0,
        "code_slot_name": ""
    },
    "origin": "LOCAL",
    "time_fired": "2021-03-31T20:20:12.260706+00:00",
    "context": {
        "id": "d7e5f60320af7ba73466f1603ea4b3c1",
        "parent_id": null,
        "user_id": null
    }
}

**Comment by firstof9** [comment]
Based on the `zwave_js_event`s you posted it seems they are no longer emitting the `code_slot` parameter.

**Comment by raman325** [comment]
well, it's a manual lock operation, there's no code slot associated with that. What's odd though with your logs from before is that even for keypad lock/unlock actions, the code slot is not included in the `zwave_js_event` so we wouldn't be able to include it in the keymaster event. That might be an upstream (zwave-js) bug. Can you try watching `zwave_js_event` and using the keypad to lock and unlock and see if you get a userId in the `parameters` section of the event?

**Comment by PrayerfulDrop** [comment]
Yes I see that.  I have a bug submitted here: https://github.com/home-assistant/core/issues/48543

I am not sure if I am explaining the issue correctly.

**Comment by raman325** [comment]
We need to open a ticket with `zwave-js`. I will open a ticket and tag you, please close the core one

**Comment by raman325** [comment]
This issue should get resolved in a future `node-zwave-js` release: https://github.com/zwave-js/node-zwave-js/issues/2206
