### ISSUE TITLE
Error executing script

### ISSUE THREAD

**Issue by quadhammer** [FutureTense/keymaster#149]
So I have migrated to the new JS Z wave integration, and the keymaster integration is working really well, thanks, but I noticed in the logs I had these two errors:

I completely uninstalled the integration, and started from scratch, but the error seems to persist.

```
Logger: homeassistant.components.automation.office_doorlock_lock_notifications
Source: helpers/script.py:1156
Integration: Automation (documentation, issues)
First occurred: 4:13:24 PM (2 occurrences)
Last logged: 4:13:30 PM

office_doorlock Lock Notifications: Error executing script. Service not found for call_service at pos 1: Unable to find service script.office_doorlock_manual_notify

Logger: homeassistant.components.automation.office_doorlock_lock_notifications
Source: components/automation/__init__.py:416
Integration: Automation (documentation, issues)
First occurred: 4:13:24 PM (2 occurrences)
Last logged: 4:13:30 PM

Error while executing automation automation.office_doorlock_lock_notifications: Unable to find service script.office_doorlock_manual_notify
```

## System Health

version | core-2021.4.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.7
os_name | Linux
os_version | 5.4.109
arch | x86_64
timezone | Australia/Brisbane

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4463
Installed Version | 1.11.3
Stage | running
Available Repositories | 776
Installed Repositories | 27

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 5.13
-- | --
update_channel | stable
supervisor_version | supervisor-2021.03.9
docker_version | 19.03.15
disk_total | 30.8 GB
disk_used | 10.3 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.3.1), Mosquitto broker (5.1.1), Duck DNS (1.12.5), Node-RED (8.2.1), Dropbox Sync (1.3.0), ESPHome (1.16.2), Zigbee2mqtt (1.18.1-1), WireGuard (0.5.1), AdGuard Home (4.0.0), File editor (5.2.0), Network UPS Tools (0.6.2), Let's Encrypt (4.11.0), Z-Wave JS to MQTT (0.11.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 19
views | 16
mode | storage

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

Not sure if it's important or not, but I thought I would let you guys know.

Cheers

**Comment by raman325** [comment]
You need to create your own script with that ID to be called. Example and explanation here: https://github.com/FutureTense/keymaster/wiki/Notification-Example-Script

**Comment by quadhammer** [comment]
Thank you, I misunderstood that those switches needed to be on to notify Node Red, but it was just that the event name had changed to 'zwave_js_notification", and it works without the Home Assistant booleans.
