### ISSUE TITLE
Integration into a calendar for lock automation 

### ISSUE THREAD

**Issue by PrayerfulDrop** [FutureTense/keymaster#151]
**Is your feature request related to a problem? No, feature request.

**Describe the solution you'd like**
Integration with the HA calendar to enable automation of lock/entry access

**Describe alternatives you've considered**
Use to use the legacy [Zwave Lock Manager](https://community.home-assistant.io/t/zwave-lock-manager-updated/189932) for simple integration.  I am hoping that Keymaster could look at a calendar and then based on a key word enable/disable access based on date and timeframe.  

Criteria:
 - use door name that is established in the options of key master as the keyword: example - "frontdoor" in the subject line
 - use a lock code number (Code 1) OR use the name of in the lock code ("Person Name")
 - Use date and start/end time of the calendar appointment
 - do not limit to google calendars
 - do not require search/filtering within calendar (this did not work well with Zwave Lock Manager and non-google calendars)

Example of meeting entry:
Subject: frontdoor: Code 1 (or Cleaning Lady)
Date: 3/14/2019
Time: 10:00am (access to home) - 3:00pm (access is diabled)

**Comment by firstof9** [comment]
Looks like this functionality already exists in Home Assistant example: [Google Calendar](https://www.home-assistant.io/integrations/calendar.google/#using-calendar-in-automations)

**Comment by PrayerfulDrop** [comment]
How would you tell Keymaster to allow/remove access?  I can do this manually through a zwave_js call but then Keymaster and the lock would be out of sync.

**Comment by firstof9** [comment]
enable/disable the boolean
