### ISSUE TITLE
ISSUE: keymaster_lock_state_changed not fired when locked or unlocked via service

### ISSUE THREAD

**Issue by treylok** [FutureTense/keymaster#153]
**Describe the bug**
The keymaster_lock_state_changed never fires when calling lock or unlock via a service call.

**Environment (please complete the following information):**

- OS: [e.g. HassOS/Raspbian/CentOS]  HassOS
- Type of device: [e.g. RPi3/NUC/Synology] RPi4
- Home Assistant version: [e.g. 0.105.5] 2021.4.5
- Hassio/Docker/Core? HAOS
- Component version: [e.g. 0.1.2] 0.0.31

**Logs**
Paste your error logs here.
No errors

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
does the `zwave_js_notification` event fire when you call `lock` or `unlock`?

Which zwave are you using? `zwave_js` `ozw` `zwave`

**Comment by treylok** [comment]
The `zwave_js_notification` event does not fire for either `lock` or `unlock`.

I am using `zwave_js`.

**Comment by firstof9** [comment]
Sounds like an upstream issue then. (Bug in zwave_js integration, zwave-js-server, or node-zwave-js)
