### ISSUE TITLE
ISSUE: zwave platform (old OZW) still supported?

### ISSUE THREAD

**Issue by Alfiegerner** [FutureTense/keymaster#155]
**Describe the bug**

I'm trying to install this using the old zwave platform (old OZW) and config flow fails with the following error in logs:

```
Logger: homeassistant.config_entries
Source: config_entries.py:575
First occurred: 8:53:44 PM (2 occurrences)
Last logged: 8:54:16 PM

Error occurred loading configuration flow for integration keymaster: No module named 'zwave_js_server'
```

**Environment (please complete the following information):**

- OS: [e.g. HassOS/Raspbian/CentOS]  Ubuntu 20.04
- Type of device: [e.g. RPi3/NUC/Synology] Server
- Home Assistant version: [e.g. 0.105.5] 2021.4.4
- Hassio/Docker/Core? Core
- Component version: [e.g. 0.1.2] 0.0.31

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by Alfiegerner** [comment]
Closing this as this just moved to zwavejs and working fine now (and won't be able to test any fixes).

**Comment by raman325** [comment]
hmm can't explain this by looking at the code. Will have to keep an eye out for the next report, thanks anyway!

**Comment by gpambrozio** [comment]
This is happening to me as well and I'm not ready to move to zwavejs just yet. Any way I can help figure out the issue?
