### ISSUE TITLE
ISSUE: FE5999 only working for code slot 1

### ISSUE THREAD

**Issue by cbhiii** [FutureTense/keymaster#164]
**Describe the bug**
[Edited to describe issues better]
It seems that only code slot 1 is working correctly to synchronize with my lock (Schlage FE599). My lock has code slots for code 1, 3, 4, 5, 6, thru 19 (skipping code 2 - screenshot and details below).

When I try to set a code for slots other than 1, nothing seems to happen.

- OS: HassOS
- Type of system that HA is running on: RPi3
- Home Assistant version: 2021.5.3
- Hassio
- Component version: 0.0.31
- Z-Wave integration name: Z-wave JS to MQTT
- Lock make and model: Allegion CKPD FE599 (Schlage)

**Logs**
[here](https://github.com/FutureTense/keymaster/issues/164#issuecomment-839923856)

**Screenshots**
![image](https://user-images.githubusercontent.com/10853381/118021970-d300ad00-b329-11eb-9122-a88c8e9e4bd0.png)
![image](https://user-images.githubusercontent.com/10853381/118022035-e449b980-b329-11eb-8972-3f92b67de6d3.png)

**Comment by firstof9** [comment]
It's likely not skipped, the code slots don't always populate in order.

**Comment by cbhiii** [comment]
I did find code slot 2 hiding in the lock after I did a refresh.

Okay, then I guess my issue is that only Code #1 synchronizes correctly and the rest "hang" and the integration doesn't get confirmation that they are set and synchronized. What other detail should I provide to help with this troubleshooting?

**Comment by firstof9** [comment]
You can [enable debugging](https://github.com/FutureTense/keymaster/wiki/Troubleshooting#enable-debugging) and post the logs.

**Comment by cbhiii** [comment]
I tried to capture what was happening, but didn't see anything. Here are the logs from the integration on debug and from the z-wave integration on debug for a successful enable (code 1), and two unsuccessful enable tries for code 2 and code 3.

[keymaster_log_test.txt](https://github.com/FutureTense/keymaster/files/6467602/keymaster_log_test.txt)

Let me know where else i can look.

Screenshot of code two still "trying". Code 3 is the same.
![image](https://user-images.githubusercontent.com/10853381/118011368-f160ab80-b31d-11eb-8018-a1d3499cd4fb.png)

**Comment by firstof9** [comment]
Is 4 digits a valid code length? I recall these locks having a setting for 4 or 6 digit lengths.

**Comment by cbhiii** [comment]
Yeah, just 4 digits. I used 1234 for code 1, 3456 for code 2 and 5678 for code 3. The programming code is 6 digits for this lock if using the keypad.

**Comment by firstof9** [comment]
Here's a test:

Go to Configuration -> Events in HA in the `Listen to events` area enter `zwave_js_notification` and click `Start Listening`.
In another tab navigate to your Keymaster UI and change the code for slot 1, then also slot 2. Lets see if any events are generated.

Also see if any template errors are occuring in the HA Log.

**Comment by cbhiii** [comment]
Okay. I've not used this before but found it under Developer Tools > Events. I then listened to `state_changed` first to figure out how the tool works. Then I stopped it and entered in `zwave_js_notification` and started listening. I didn't see anything no matter what I did in lovelace to enable, change or disable codes in both slot 1 or slot 2.

**Comment by firstof9** [comment]
Are any template/script/automation errors showing up in your HA logs?

**Comment by cbhiii** [comment]
No errors in the home-assistant.log file. I've been tailing it all day.

**Comment by cbhiii** [comment]
I can remove the installation and re-install it if you think that would be helpful to try, but I'll wait to hear back.

**Comment by firstof9** [comment]
You can give it a shot.

**Comment by cbhiii** [comment]
Keymaster integration removed and re-installed: **no change in issue**

Let me know where else I can look if you have any things for me to check. Thanks.

Actions performed for the record:
- deleted keymaster integration (Configuration > integration)
- removed add-on via HACS menu (HACS > integrations > uninstall)
> restarted HA
- confirmed entities removed and HA stable with no errors in logs
> rebooted host <
- followed wiki for reinstallation of keymaster from HACS menu (HACS > integrations)
> restarted HA
- installed integration and configured (screenshot below)
- waited for generation of sensors (seen in HA log)
- waited for package file generation complete message
> restarted HA
- everything looks good again in frontend menu
- ran tests from above with [listener](https://github.com/FutureTense/keymaster/issues/164#issuecomment-839993596), and then with [HA logs on debug and Z-wave logs](https://github.com/FutureTense/keymaster/issues/164#issuecomment-839923856) running. No change. Only code 1 acts as expected. No output from the listener. Only code 1 shows up in log files.

(no lovelace frontend changes were made during the reinstall)

Configuration screenshot
![image](https://user-images.githubusercontent.com/10853381/118038977-cab26d00-b33d-11eb-8e2c-94c348ef5e37.png)

**Comment by cbhiii** [comment]
So... I kept poking at it and trying this and that. Within the Z-wave JS to MQTT UI panel I finally did a "user code - refresh" on that screen. 
![image](https://user-images.githubusercontent.com/10853381/118042092-a5bff900-b341-11eb-8174-3b3ae01ea678.png)

Then my missing code slot 2 appeared along with things starting to work everywhere! I have no idea how that would have prevented the Keymaster integration from "trying" as nothing was seen in the logs, but my guess is that the lock was not reporting that it had additional code slots to your app in some way until I refreshed the lock with my z-wave controller. That's why the app wasn't trying is my guess.

As you can see now the debug log shows all 19 code slots being checked every so often where it was only seeing slot 1 beforehand.
![image](https://user-images.githubusercontent.com/10853381/118042541-37c80180-b342-11eb-8545-5678df5c26ac.png)

**Comment by cbhiii** [comment]
Perhaps an incomplete/corrupted z-wave interview of the node is to blame for the issues. I've "healed" it so it finds a better neighbor to relay messages through. I believe things are working as expected now. Thank you for your time.
