### ISSUE TITLE
childlocks - add “parent” dropdown listbox

### ISSUE THREAD

**Issue by FutureTense** [FutureTense/keymaster#169]
Add “parent” dropdown listbox, that is populated with `(none)` as the first (and default) item.  The rest of the items should be the names of every keymaster integration that is **not** itself a child lock.  In other words, any lock whose parent dropdown value is set to  `(none)` is a possible parent lock and should be added to the dropdown. Any lock that has a parent dropdown selected other than `(none)` by definition is a child lock and shouldn’t appear as a possible parent.

Don’t forget to exclude the current lock’s name from the dropdown list, e.g, you create frontdoor and backdoor and they each have their parent set to `(none)`.  If you attempt to modify either of them, their dropdown items should **exclude** the integration’s lock name because a lock shouldn’t be able to be a parent to itself.

Around line 300 of services.py use variables for the source file names.  For parent locks, the source should be:

* keymaster_common.yaml
* keymaster.yaml
* lovelace.code
* lovelace.head

and the child locks will ultimately use:

* keymaster_common_child.yaml
* keymaster_child.yaml
* lovelace _child.code
* lovelace _child.head

However, for now use the same file names for both locks, e.g. keymaster_common.yaml because those files do not exist yet.  I’ll change the file names in services.py as I implement them

Please commit to [childlocks](https://github.com/FutureTense/keymaster/tree/childlocks) branch

**Comment by FutureTense** [comment]
I’ll also need a Python blurb from you to determine if an integration is a child and what is the parent name.  Something like

```
? (is this integration a child)
? (parentName)
```

**Comment by firstof9** [comment]
Here'd be a bool:

```python
def is_child(hass: HomeAssistant, name: str) -> bool:
    """Generate the package files."""
    config_entry = next(
        (
            hass.config_entries.async_get_entry(entry_id)
            for entry_id in hass.data[DOMAIN]
            if hass.data[DOMAIN][entry_id][PRIMARY_LOCK].lock_name == name
        ),
        None,
    )
    primary_lock: KeymasterLock = hass.data[DOMAIN][config_entry.entry_id][PRIMARY_LOCK]
    return bool(primary_lock.parent)
```
and here's returning the name:
```python
def parent_name(hass: HomeAssistant, name: str) -> str:
    """Generate the package files."""
    config_entry = next(
        (
            hass.config_entries.async_get_entry(entry_id)
            for entry_id in hass.data[DOMAIN]
            if hass.data[DOMAIN][entry_id][PRIMARY_LOCK].lock_name == name
        ),
        None,
    )
    primary_lock: KeymasterLock = hass.data[DOMAIN][config_entry.entry_id][PRIMARY_LOCK]
    return primary_lock.parent
```

**Comment by FutureTense** [comment]
@firstof9 can you move the parent dropdown to the top of the screen and add an appropriate label
