### ISSUE TITLE
Missing Comma

### ISSUE THREAD

**Issue by TheFuzz4** [FutureTense/keymaster#171]
https://github.com/FutureTense/keymaster/blob/36fbc2185e748ff0d2e4f2e7c7521cfc3d75884b/custom_components/keymaster/manifest.json#L23

So when doing a new install of keymaster last night the , was missing from the end of the version line in the manifest. 

I added the comma in there and then everything was happy and the integration showed up in the integrations list within HA as it should.  I don't know if this is the correct release for this issue but its the only one I could find that was missing the comma in there.  Thanks.

**Comment by firstof9** [comment]
Which install method did you use?

**Comment by firstof9** [comment]
Also that's an old commit

**Comment by TheFuzz4** [comment]
I installed via HACS.  Yeah I figured that was an old commit but it was the only one I could find that was missing a comma.

**Comment by firstof9** [comment]
All the HACS and HASSfest checks come up good, there shouldn't be any issues.

**Comment by dougbillings** [comment]
Just installed today and issue persist. Installed on HA OS via HACS.

**Comment by firstof9** [comment]
Please provide additional information.

**Environment (please complete the following information):**

- Home Assistant version: [e.g. 0.105.5]
- Component version: [e.g. 0.1.2]

**Comment by tykeal** [comment]
Strangest thing. Was working fine for me but my HA locked up on me and when I finally managed to get back onto the system I was seeing the same error that was reported here.

Here's the information for my particular setup:

HA OS v5.13
HA version: core-2021.5.5
KeyMaster version: v0.0.32
Installed via HACS which is at version 1.12.3

I manually corrected the manifest and restart and everything was fine, but just to test I had HACS reinstall v0.0.32 and it stripped that comma out again.

**Comment by firstof9** [comment]
Odd as it's currently valid JSON and adding a comma throws errors on the checks.
I am not seeing this error in Home Assistant.

EDIT: I see the issue, it's part of the automatic versioning it's clearing the comma out.

**Comment by tykeal** [comment]
@firstof9 should probably reopen this issue then.

**Comment by firstof9** [comment]
Hotfix release should have solved it.
