### ISSUE TITLE
ISSUE: No 'version' key in the manifest file - needed for HA 2021.6

### ISSUE THREAD

**Issue by cbhiii** [FutureTense/keymaster#173]
**Describe the bug**
HA log error during boot-up saying it needs a version key in the manifest file or it will no longer work on HA 2021.6.

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: RPi3
- Home Assistant version: 2021.5.4
- Hassio
- Component version: 0.0.32
- Z-Wave integration name: N/A
- Lock make and model: N/A

**Logs**
`2021-05-21 21:37:07 ERROR (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'keymaster'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'keymaster'`

**Comment by firstof9** [comment]
The mainfest file contains the version.
