### ISSUE TITLE
[Feature Request] Prepend "Keymaster" to all automatically generated automations

### ISSUE THREAD

**Issue by libots** [FutureTense/keymaster#174]
**Is your feature request related to a problem? Please describe.**
The generated automations take of a *lot* of space in my automations section (I've got four locks) and are jumbled all over alphabetically: some start with the name of the lock (e.g., Front, Back, etc.), others begin with "synchronize_codeslot..."

I try to organize my automations logically alphabetically, and it just makes it a mess.

**Describe the solution you'd like**
 I'd love to group them in one spot just by putting "Keymaster" (or maybe even better "zzzKeymaster" to keep them at the bottom) in front of them.

**Describe alternatives you've considered**
I could fork the project and do it on my own, but I thought others might enjoy this and I keeping up a separate fork isn't the ideal solution for me.

**Additional context**
I don't mind making doing the work on this and putting in a pull request, I just thought I'd see what everyone's thoughts are first. Thanks!

**Comment by tykeal** [comment]
@libots sounds interesting and I would like to see it as well.

My suggestion, add it as a configuration variable. Default it to 'Keymaster_' but that would allow others to set their desired prefix.

**Comment by raman325** [comment]
I'm not sure about the configuration variable, we can add it later but I think the namespacing provides more immediate value than letting the user control the namespace (you already do that to an extent with the lock name).

Otherwise this is a no brainer - I had actually added something like this a while ago but then we had to revert some things and I haven't had a chance to re-add it. I'd like to rename the entities too to make them more consistent but that's harder to do without making it a breaking change, so I will defer that one for now.

**Comment by maggar** [comment]
Until HA UI provides an option to mark automations as hidden from the UX (e.g. system), I think it would be helpful to also prepend a tilde (e.g. ~KeyMaster-) to the automation name, so all of these auto-generated automations show up at the end of the list.

**Comment by FutureTense** [comment]
I endorse this as well.  It should probably be done in conjunction with issue 175.

**Comment by FutureTense** [comment]
> Until HA UI provides an option to mark automations as hidden from the UX (e.g. system), I think it would be helpful to also prepend a tilde (e.g. ~KeyMaster-) to the automation name, so all of these auto-generated automations show up at the end of the list.

That’s a bridge too far

**Comment by FutureTense** [comment]
Adding prefix for scripts as well.

Is it worth doing this for all entities “

**Comment by markaggar** [comment]
> That’s a bridge too far

Not sure why you think that.  I'm trying to avoid the case where I have to scroll through a gazillion Keymaster automations/scripts that show up in the middle of the list.  It's nice to have them altogether, but frankly most of us would rather not see them at all, so a ~ can take care of that to some extent (i.e. if I see anything beginning with ~, I've scrolled down too far).

**Comment by FutureTense** [comment]
> > That’s a bridge too far
> 
> Not sure why you think that. I'm trying to avoid the case where I have to scroll through a gazillion Keymaster automations/scripts that show up in the middle of the list. It's nice to have them altogether, but frankly most of us would rather not see them at all, so a ~ can take care of that to some extent (i.e. if I see anything beginning with ~, I've scrolled down too far).

I tried renaming with a tilde in front, and HA ignores it in developer states.  Try it yourself and rename some of your automations with ~xxx and see what happens.

**Comment by FutureTense** [comment]
@raman325 or @firstof9 can you take a look at the prefix branch and see if the tests work?

**Comment by libots** [comment]
I actually kinda like the tilde idea, but even better (though admittedly a bit more complicated) would be @tykeal's idea of the variable. I was surprised to learn that the tilde sorts to the bottom (I always thought most special characters went at the top). That being said, anything at all would probably be a good placeholder.

Edit: just saw the part about it making automations get ignored. I'm not above zzzKeymaster, though.

**Comment by markaggar** [comment]
I just created a script and an automation that both begin with a tilde.  The automation was able to see the script, and they both sort fine in the UX. Curiously, the ~ is ignored for the service call, but the log book shows it actually called the script with the ~.

~test script turned off by ~test automation
2:31:44 PM - 3 minutes ago
~test script turned on by ~test automation
2:31:44 PM - 3 minutes ago
~test script started by ~test automation
2:31:44 PM - 3 minutes ago
~test automation has been triggered by service automation.trigger
2:31:44 PM - 3 minutes ago - Show trace


```
test_script:
  alias: ~test script
  sequence:
  - type: turn_on
    device_id: b0d91abd199494cea3a587a708aba4db
    entity_id: switch.master_bed_fan
    domain: switch
  mode: single

- id: '1624570051648'
  alias: ~test automation
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.turn_fans_on_upstairs
    to: 'on'
  condition: []
  action:
  - service: script.test_script
  mode: single
```

**Comment by firstof9** [comment]
> can you take a look at the prefix branch and see if the tests work?

All the tests passed on the `prefix` branch

**Comment by FutureTense** [comment]
Not sure how y’all are doing it, but I don’t have a problem with all of the keymaster items in the UI dev.  Mostly because I filter to what I’m looking for.  But even so, adding a ~ doesn’t do jack for me.  It still shows the automation without the tilde.

**Comment by firstof9** [comment]
They're using the `alias` option.
