### ISSUE TITLE
[Feature Request] Remove '-' from start of <lockname>_lovelace

### ISSUE THREAD

**Issue by theOrakle** [FutureTense/keymaster#175]
**Is your feature request related to a problem? Please describe.**
Trying to use lockname_lovelace in an !include

**Describe the solution you'd like**
Here is what I did:
```
title: Locks
views:
- !include ../packages/keymaster/deck/deck_lovelace
- !include ../packages/keymaster/patio/patio_lovelace
- !include ../packages/keymaster/shed/shed_lovelace
- !include ../packages/keymaster/study/study_lovelace
```

**Describe alternatives you've considered**
I have stripped the "-" out of the beginning of the lockname_lovelace files

**Additional context**
I'm sure I'm doing it wrong as I can see the intent for the structure/indentation of lockname_lovelace.  At first I was thinking !include_dir_merge_list but you would have structured the files differently to be packages/keymaster/lovelace.  Any clue on what I'm doing wrong or what you intended would be appreciated above and beyond the truly awesome contribution itself

**Comment by raman325** [comment]
Lovelace doesn't support !include directives as far as I know. You have to copy and paste the contents of the file directly into your lovelace config. The reason we generate the file is to make it easier for you to perform this action, we have no way of automatically updating lovelace configs either

**Comment by theOrakle** [comment]
Lovelace in YAML mode absolutely supports includes.  The above solution works just fine, I just needed to remove the "-" from the generated file and you can see how I included it above.

**Comment by firstof9** [comment]
Swapping - for _ should be pretty trivial.

**Comment by raman325** [comment]
well, TIL, thanks!

**Comment by FutureTense** [comment]
@theOrakle so your saying if you replace - with _ it will work?

**Comment by firstof9** [comment]
Yes that's what he's saying.

**Comment by FutureTense** [comment]
`- !include ../packages/keymaster/study/study_lovelace
`
The UI rejected that.

`Unable to parse YAML: YAMLException: unknown tag !<!include> (7:64) `

**Comment by FutureTense** [comment]
Ah.. storage mode vs yaml.  Hmmm

**Comment by raman325** [comment]
just an FYI, this is a good idea for a change but it's a bit more work than it sounds. When we make the change we will need to look for files with `-`'s and delete them when we generate the new files with `_`'s

**Comment by firstof9** [comment]
Rechecking the code looks like it's always been `{lockname}_lovelace` for the filenames, no `-` are involved.

https://github.com/FutureTense/keymaster/blame/6cfb531fe52432a84b4326c7cf534b262bb12a18/custom_components/keymaster/services.py#L303

and 

https://github.com/FutureTense/keymaster/blame/6cfb531fe52432a84b4326c7cf534b262bb12a18/custom_components/keymaster/services.py#L316

**Comment by raman325** [comment]
Could this have something to do with the way you named your lock? We don't strip `-`'s so if you had that in your lock name that would introduce it into the path

**Comment by theOrakle** [comment]
Have a look at the first non blank character in the Lovelace file it is a “-“.  All I’m asking is to replace the “-“ with a “ “.  This will allow for advanced users with autogenerated yaml to dynamically build dashboards.

Maybe you should re-read my original statements.  I am unsure how to make any clearer for you.  It is obviously not intended to be used as an !Include in yaml mode dashboard based on the questions.

**Comment by firstof9** [comment]
Oh so you're talking about this part here?

https://github.com/FutureTense/keymaster/blob/b13cba4a898f4ccea9b9885a9520e93ccd0d6ce4/custom_components/keymaster/lovelace_child.head#L1

Remove the `-` next to `title` right?

**Comment by theOrakle** [comment]
Yes sir

**Comment by FutureTense** [comment]
This needs to be done for `lovelace.head` as well?  I see no harm, especially as there can be only one title element anyways.

**Comment by FutureTense** [comment]
I just tried removing this and building a new child integration.  It fails the Lovelace check.  @theOrakle have you actually tested this?  If you have a working `lovelace_child.head`, I’d like to see it.

**Comment by theOrakle** [comment]
I’m currently on Vacation - give me 2-3 days. 

I didn’t alter anything but the the one character in the Lovelace file generated mentioned in my original post

**Comment by FutureTense** [comment]
Please do.  I don’t have the time to chase down changing requests.  Btw, I removed your cell # from your last post.  Please protect your online anonymity.

**Comment by theOrakle** [comment]
Thanks for cleaning my reply up.

**Comment by theOrakle** [comment]
I 'm not sure how else to communicate the request, so I will close it...

For anyone else that is wanting to dynamically include this in the dashboards.

Create a dashboard in yaml mode: (Change the path obviously)
```
title: Locks
views:
- !include ../packages/keymaster/deck/deck_lovelace
- !include ../packages/keymaster/foyer/foyer_lovelace
- !include ../packages/keymaster/patio/patio_lovelace
- !include ../packages/keymaster/shed/shed_lovelace
- !include ../packages/keymaster/study/study_lovelace
```
One-liner to fix the yaml generated: (Change the path obviously)
`find /opt/homeassistant/config/packages/keymaster -name "*_lovelace" -exec sed -i 's/^  -/   /g' '{}' \;`

This will nee to be re-executed every time you regenerate the lovelace files.

**Have fun**
