### ISSUE TITLE
ISSUE: Child locks need doc

### ISSUE THREAD

**Issue by chrismccracken** [FutureTense/keymaster#183]
**Describe the bug**
I am not able to find any documentation on what the child locks feature does or how it works aside from a brief reference to the config file. What problems or use cases does it solve? I understand there is a refactoring effort in progress on the technical side, so this may be a work-in-progress.

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: NUC
- Home Assistant version: core-2021.6.3
- Hassio/Docker/Core? Hassio
- Component version: [1.12.4 (via HACS)
- Z-Wave integration name:  zwave_js
- Lock make and model: [e.g. Schlage BE469]

**Logs**
N/A

**Screenshots**
N/A

**Additional context**
My specific use case that [might] be solved via child locks is having a front door and back door lock that use the same common set of user names/PIN codes. I'd like to manage both locks together rather then separately. Are child locks a way to solve this, and how should the locks be related as parent:child?

**Comment by firstof9** [comment]
> My specific use case that [might] be solved via child locks is having a front door and back door lock that use the same common set of user names/PIN codes. I'd like to manage both locks together rather then separately.

This is exactly what the 'child locks' feature is for.
The wiki hasn't been updated yet, but to summarize you would set your back door lock's parent config to the front door lock, and the codes _should_ be inherited/synced between them.

**Comment by djbr22** [comment]
This isn't an 'official' doc from the dev, but I documented how I set child locks as of 7/18/21, so it should be accurate and up to date. You are welcome to include the link in your wiki if you'd like: https://smarthomepursuits.com/add-a-child-lock-to-keymaster-in-home-assistant/
