### ISSUE TITLE
ISSUE: Each keymaster upgrade in HACS requires a zwave-js device re-interview

### ISSUE THREAD

**Issue by claytongreer** [FutureTense/keymaster#185]
**Describe the bug**
It appears that any keymaster version upgrade in HACS results in a loss of keymaster functionality that can only be resolved by re-interviewing the lock in zwave-js. The problem can manifest itself either by trying to set a code in an empty slot (logs will show usercodeID doesn't exist) or by keymaster being unable to connect (stays in a continuous "connecting" state with no log error) to slots that have advanced schedules by day and time of week where the PIN state should be set. I can update or restart zwave-js independent of a keymaster upgrade without problem, same for core updates. The only common action that I've recognized will trigger this behavior is a keymaster update.  Once the device is re-interviewed, full keymaster functionality is restored with no other reset/restart necessary. 

**Environment (please complete the following information):**

- OS: [e.g. HassOS/Raspbian/CentOS] HassOS
- Type of system that HA is running on: [e.g. RPi3/NUC/Synology] Windows 8.1/VM VirtualBox
- Home Assistant version: [e.g. 0.105.5] most recent defect appearance 2021.6.3
- Hassio/Docker/Core?
- Component version: [e.g. 0.1.2]
- Z-Wave integration name:  zwave_js  0.1.25
- Lock make and model: Schlage BE469
- HACS 1.12.4
- Keymaster 0.0.47
[Schlage interview zwave-js 2021-6-2.txt](https://github.com/FutureTense/keymaster/files/6641624/Schlage.interview.zwave-js.2021-6-2.txt)
[Schlage interview zwave-js 2021-6-11 after HACS upgrade.txt](https://github.com/FutureTense/keymaster/files/6641625/Schlage.interview.zwave-js.2021-6-11.after.HACS.upgrade.txt)

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Keymaster doesn't interact with zwave-js in a way that would cause command classes to be altered.

The diff between your two txt files shows that there is a missing property key for one of the usercode slots, this has been found to cause issues with the code slot sensors.

**Comment by claytongreer** [comment]
It seems perfectly reasonable that the layers would be sufficiently separated. I was initially thinking of reporting this problem under zwave-js, particularly because I was previously updating keymaster versions in combination with changes to other components.

 I'm only re-interviewing the lock when keymaster functionality fails. I assume that nothing in zwave-js or other HA components will initiate a device re-interview after one has been initially completed for a device. I've intentionally added some zwave devices, restarted zwave-js, restarted the server multiple times over several days, updated core without changing the keymaster version, and keymaster functionally continues to work flawlessly. However, as soon as I update keymaster versions, I will immediately experience problems as described with keymaster functionality. And I updated to keymaster v0.47 without changing any other component, and I experience functionality problems as described. 

I can't get updates or restarts to other components to cause keymaster functionality to fail, but I can always get a keymaster version update to fail in such a way that the lock has to be re-interviewed in order to recover the properties expected by the configuration scripts. What are the alternatives that might explain such a seemingly tight causality? Bad disk sectors or memory bits that cause the lock properties to drop? Another process that is overwriting device state at the same time? Any suggestions on a more apt forum to post this?

**Comment by claytongreer** [comment]
The txt file titled 2021-6-2 is a network dump of the lock immediately following a lock re-interview on June 2. I performed a re-interview at that time in order to fix a problem I was experiencing in keymaster that was triggered by a keymaster version upgrade I performed earlier on June 2. Note that the interview stage is complete. 

Between June 2 and June 11 I programmed and changed the lock slots numerous times, made numerous changes to my zwave network, and restarted zwave-js serveral times, and restarted by HA server several times, all without impact to keymaster functionality.  Then on June 11, I performed an upgrade to keymaster 0.47, immediately began experiencing keymaster problems, and then dumped the lock properties for the zwave network into the txt file labeled 2021-6-11. I posted the two txt files as evidence that the June 11 network dump is indeed missing properties which were present after the June 2 interview. I'm thinking this may likely be due to the keymaster version upgrade I performed on June 11 because at this time I'm not aware of what else would likely have caused the lock properties to have gotten dropped.

Thinking this through, I'll take a dump of the network immediately before next upgrading keymaster, and a dump immediately after, in order to better isolate the problem.

**Comment by EricE** [comment]
I just found this issue when looking for the reason why PIN Status was staying in the Connecting state when trying to add a new PIN (I'm using the latest Z-Wave JS, 0.1.25).   I installed Keymaster (0.0.47) last night, tried to put in a new code, and this morning it was still in the Connecting state.   I reinterviewed the Schlage Connect (BE469ZP), cycled the Enabled input and "PIN synchronized with lock" went to On and the code was set in the lock.  I added another code entry and it synchronized quickly.  When it wasn't working, other than the two default codes in Code 1 & 2, the others where showing as disconnected.
![image](https://user-images.githubusercontent.com/126238/121817241-fffbf480-cc34-11eb-8687-e7d08d479812.png)

It seems a little strange that the all of the PIN synchronized statuses are set to On even though I've not added a code?
![image](https://user-images.githubusercontent.com/126238/121817213-d511a080-cc34-11eb-97ed-dc5ef1652a2b.png)

The only logs I know to look at are from Z-wave JS, how are you doing a "network dump"?  I'm a hardware guy and still learning how to debug HA.  NVM, I found it under "Manage your Z-Wave Network", I've attached the dump.
[zwave_js_dump.txt](https://github.com/FutureTense/keymaster/files/6644401/zwave_js_dump.txt)

**Comment by firstof9** [comment]
> It seems a little strange that the all of the PIN synchronized statuses are set to On even though I've not added a code?

No, disabled = no code, so that's synchronized.

The BE469 locks fail to adhere to the zwave specifications that lock are to send the slot codes when requested, these locks report `*******` instead, so we have a workaround in place to prevent flooding the locks with add/remove code commands.

**Comment by firstof9** [comment]
Are you @EricE and @claytongreer using a supervised install with the addon or stand alone container for `zwavejs2mqtt`?

**Comment by EricE** [comment]
I'm using HASS OS on a NUC and Keymaster installed through HACS.  I've tried zwavejs2mqtt but it has a conflict accessing the HUSBZB-1 stick so I uninstalled it; just using the Z-Wave JS add-on.

**Comment by claytongreer** [comment]
I'm not using zwavejs2mqtt although early on I did use Supervisor to install it. I ended up uninstalling it.

**Comment by firstof9** [comment]
Please post your `System Health` from the Configuration -> Info screen in Home Assistant.

Example:
![image](https://user-images.githubusercontent.com/1105672/121819836-2d9c6a00-cc44-11eb-8387-f44f1109f669.png)

## System Health

version | core-2021.6.3
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.4.0-74-generic
arch | x86_64
timezone | America/Phoenix

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4654
Installed Version | 1.12.4
Stage | running
Available Repositories | 844
Installed Repositories | 56

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 43

</details>

<details><summary>Lovelace</summary>

dashboards | 4
-- | --
resources | 41
views | 49
mode | storage

</details>

**Comment by EricE** [comment]
## System Health

version | core-2021.6.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.42
arch | x86_64
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4928
Installed Version | 1.12.4
Stage | running
Available Repositories | 843
Installed Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | June 26, 2021, 5:00 PM
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | false
google_enabled | false
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.0
docker_version | 20.10.6
disk_total | 30.8 GB
disk_used | 12.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Check Home Assistant configuration (3.7.1), File editor (5.3.1), Samba share (9.5.1), Visual Studio Code (3.4.1), Log Viewer (0.11.0), Node-RED (9.1.4), Terminal & SSH (9.1.3), Mosquitto broker (6.0.1), Portainer (1.5.1), Home Assistant Google Drive Backup (0.104.3), Z-Wave JS (0.1.25), chrony (2.1.0), Glances (0.12.2), ESPHome (1.18.0), InfluxDB (4.1.1), Grafana (7.0.0)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 5
views | 10
mode | storage

</details>

**Comment by claytongreer** [comment]
Note: I updated core to 2021.6.4 earlier this afternoon, along with updates to node-red, samba share and portainer. At the end of all these updates, I checked keymaster and found one of my slots was in a continuous "disconnecting" status which it had not been prior to this string of updates. Doing another re-interview on the lock resolved the problem.  Looks like I'll need to regularly check keymaster functionality and frequently take zwave network dumps to better isolate what might be triggering this. Not sure which group to transfer this issue to.

## System Health

version | core-2021.6.4
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
virtualenv | false
python_version | 3.8.9
os_name | Linux
os_version | 5.10.42
arch | x86_64
timezone | America/Los_Angeles

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4948
Installed Version | 1.12.4
Stage | running
Available Repositories | 842
Installed Repositories | 6

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 6.0
-- | --
update_channel | stable
supervisor_version | supervisor-2021.06.0
docker_version | 20.10.6
disk_total | 30.8 GB
disk_used | 6.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.12.5), File editor (5.3.1), Visual Studio Code (3.4.1), Z-Wave JS (0.1.25), Samba share (9.5.0), SSH & Web Terminal (8.2.3), FTP (4.1.0), Home Assistant Google Drive Backup (0.104.3), Portainer (1.5.0), Node-RED (9.1.3)

</details>

<details><summary>Lovelace</summary>

dashboards | 1
-- | --
resources | 4
views | 2
mode | storage

</details>

**Comment by firstof9** [comment]
This very much sounds like an issue with the addon's cache getting altered/corrupted.

**Comment by SP410** [comment]
I am having the same issue now that I know what to look for.

**Comment by FutureTense** [comment]
This isn’t something we can address now.
