### ISSUE TITLE
ISSUE: invalid config for input_text

### ISSUE THREAD

**Issue by hanerd** [FutureTense/keymaster#192]
**Describe the bug**
Adding a second integration with a parent lock causes an invalid configuration.

**Environment (please complete the following information):**
Homeassistant Docker 2021.6.6 on Ubuntu 18

ZwaveJS2MQTT

Schlage BE4869ZP

**Logs**
```Invalid config for [input_text]: invalid slug second_rear_Second_Floor_parent (try second_rear_second_floor_parent) for dictionary value @ data['input_text']. Got OrderedDict([('second_rear_name_1', OrderedDict([('name', 'Name')])), ('second_rear_pin_1', OrderedDict([('name', 'PIN'), ('mode', 'text')])), ('second_rear_name_10', OrderedDict([('name', 'Name')])), ('second_rear_pin_10', OrderedDict([('name', 'PIN'), ('mode', 'text')])), ('second_rear_name_2', OrderedDict([('name', 'Name')])), ('second_rear_pin_2', OrderedDict([('name', 'PIN'), ('mode', 'text')])), ('second_rear_name_3', OrderedDict([('name', 'Name')])), ('second_rear_pin_3', OrderedDict([.... (See ?, line ?). Please check the docs at https://www.home-assistant.io/integrations/input_text```

**Additional context**
This seems to only occur when adding a child lokc.

**Comment by firstof9** [comment]
@raman325 looks like we need to `.toLower` the lock names eh (thoughts)?

@hanerd rename your lock to `second rear second floor parent` no capital letters, see if that fixes it please.

**Comment by hanerd** [comment]
@firstof9 haha, yeah.  I was just playing with that.  I actually thought it was the underscores, but looks like it's the capitalization.

Works for me without the capitals!

**Comment by firstof9** [comment]
Excellent, let's keep this open for tracking. Thank you for testing.
