### ISSUE TITLE
ISSUE: Keymaster does not show up in Integration

### ISSUE THREAD

**Issue by wingman1487** [FutureTense/keymaster#199]
**Describe the bug**
Running HA on a Supervised Docker installation, everything is running fine, other integration from HACS have been working ok, but this one really doesn't like me.  I have followed the steps trying to get this setup plus some.  I don't think this should be that difficult, but I'm stuck scratching my head here.

1. Created the packages directory in the same area as the configuration.yaml
2. Added the below to the configuration.yaml (properly formatted, GitHub isn't taking into account spacing and carriage return)
`homeassistant:
  packages: !include_dir_named packages`
3. Installed the keymaster via HACS
4. Restarted HA

When I go to the Integrations to search for 'keymaster' nothing comes up.

After the above when looking at the packages directory I created I am not seeing anything added there.  However, when digging into the ../custom_components I do see that keymaster directory has been created there and all the files are there.  I've then tried to do below

1. Move this keymaster directory from custom_components to the packages directory
This results in all sorts of duplicate and not found errors when checking the Configuration before restarting, below is just a snip.
- Package keymaster_child setup failed. Component input_number has duplicate key 'name'
- Package keymaster_child setup failed. Component input_datetime has duplicate key 'name'
- Package keymaster_child setup failed. Component input_text has duplicate key 'name'
- Package keymaster_child setup failed. Component input_boolean has duplicate key 'name'
- Package keymaster_common_child setup failed. Component input_boolean has duplicate key 'name'
- Package keymaster_common_child setup failed. Component input_text has duplicate key 'name'
- Package keymaster_common_child setup failed. Component timer has duplicate key 'name'
- Package services setup failed. Component generate_package Integration 'generate_package' not found.
- Package services setup failed. Component add_code Integration 'add_code' not found.
- Package services setup failed. Component clear_code Integration 'clear_code' not found.
- Package services setup failed. Component refresh_codes Integration 'refresh_codes' not found.
2. Moving the keymaster directory back to custom_components from package directory
This has the same result in not finding 'keymaster' in Integrations but has no more error when checking the Configuration.
3. Changing the configuration.yaml entry to point to the custom_components directory
This yields the same results as case 1 with duplicates and not found errors
`homeassistant:
  packages: !include_dir_named custom_components`

**Environment (please complete the following information):**

- OS: Debian w/ Supervised Docker Container
- Type of system that HA is running on: Dell R620
- Home Assistant version: 2021.7.2
- Hassio/Docker/Core? Docker
- Component version: 0.0.55
- Z-Wave integration name: zwave_js
- Lock make and model: Schlage BE469NX

**Comment by raman325** [comment]
Try doing a hard refresh in your browser before trying to setup the integration. The front end caches aggressively and so you may be loading an old list of integrations

**Comment by wingman1487** [comment]
> Try doing a hard refresh in your browser before trying to setup the integration. The front end caches aggressively and so you may be loading an old list of integrations

Ok, it would be funny if it wasn't so sad, after clearing my cache I was able to get this working... Thank raman325!
