### ISSUE TITLE
ISSUE: Notifications not working based on example

### ISSUE THREAD

**Issue by srpomeroy** [FutureTense/keymaster#201]
**Describe the bug**
I am having a hard time getting notifications to fire. In my troubleshooting, I discovered that the config in the autogenerated keymaster_common.yaml may have a discrepancy on the following lines:
https://github.com/FutureTense/keymaster/blob/main/custom_components/keymaster/keymaster_common.yaml#L154
https://github.com/FutureTense/keymaster/blob/main/custom_components/keymaster/keymaster_common.yaml#L174
https://github.com/FutureTense/keymaster/blob/main/custom_components/keymaster/keymaster_common.yaml#L190
I believe `LOCKNAME_manual_notify` should be replaced with `keymaster_LOCKNAME_manual_notify`.

The wiki and tests would need to be updated to follow suit.
https://github.com/FutureTense/keymaster/wiki/Notification-Example-Script
https://github.com/FutureTense/keymaster/blob/main/tests/yaml/frontdoor/frontdoor_keymaster_common.yaml

**Environment (please complete the following information):**

- OS: [e.g. HassOS/Raspbian/CentOS] **Home Assistant OS 6.1**
- Type of system that HA is running on: [e.g. RPi3/NUC/Synology] **RPi4**
- Home Assistant version: [e.g. 0.105.5] **2021.7.3**
- Hassio/Docker/Core? **Hassio**
- Component version: [e.g. 0.1.2] **0.0.55**
- Z-Wave integration name: [e.g. zwave_js] **zwave_js**
- Lock make and model: [e.g. Schlage BE469] **Schlage BE469**

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by srpomeroy** [comment]
I would be happy to submit a PR for the code changes and add some additional color to the wiki. I just wasn't sure what the proper guidelines are for contributing.

**Comment by firstof9** [comment]
I'm not sure if that was accidental or intentional as that's technically a breaking change.

Feel free to fire off a PR.
