### ISSUE TITLE
Beta version required? 

### ISSUE THREAD

**Issue by Epod** [FutureTense/keymaster#210]
https://github.com/FutureTense/keymaster/blob/9eb79e1f0e5fdae236d99d55737eadae6cdd731b/hacs.json#L17

HACS will not allow installs unless a beta version of Home assistant is installed. Additionally, selecting any of the older version now prompt the same error, that a beta version is required.

**Comment by raman325** [comment]
There are breaking changes in 2021.8.0 that prompted us to add this, but I take your point. I converted the breaking change release to a pre-release for those who need it, and will revert the min version change until 2021.8.0 launches on Wednesday.
