### ISSUE TITLE
ISSUE: Child locks do not convert spaces to underscores when parent lock name has spaces

### ISSUE THREAD

**Issue by jordandrako** [FutureTense/keymaster#229]
**Describe the bug**
When you name a parent lock with capital letters and spaces, then add a child lock to it, the generated helpers and automations do not transform the string into the correct case.

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: RPi4
- Home Assistant version: 2021.9.7
- Hassio
- Component version: 0.0.63
- Z-Wave integration name: zwave_js via zwavejs2mqtt
- Lock make and model: Schlage BE469ZP

**Screenshots**
![image](https://user-images.githubusercontent.com/7110658/134408744-b0cb91c4-5b22-460d-ae08-c3bb42b6866d.png)
![image](https://user-images.githubusercontent.com/7110658/134408803-23f37da1-2997-44a1-b97f-54d724461403.png)

![image](https://user-images.githubusercontent.com/7110658/134408670-195a8e7e-34df-4b1f-9351-6009caefce9c.png)

**Additional context**
A simple find and replace for the string across the child lock config files fixes the issue, but it should be parsed correctly when generating.

**Comment by firstof9** [comment]
Looks like we missed a `slugify`

**Comment by firstof9** [comment]
This should be resolved in 0.0.75
