### ISSUE TITLE
Errors adding child lock with 0.71 & 0.72

### ISSUE THREAD

**Issue by dadcoachengineer** [FutureTense/keymaster#238]
Initially ran into this error after installing a child lock. The lock had no issue syncing codes from the parent lock but obviously with this error you are unable to restart HA. It looks like it failed to add a referenced entity.

![fbe42223a85fc72d6bab9fe777c66deb486009d4_2_958x1000](https://user-images.githubusercontent.com/6666082/136676709-9d236e7e-97af-4f1c-9f32-9d8f13888019.jpeg)

0.72 was committed with a fix for this error but then brought its own issue causing a failure to install the config for the child lock making it unusable.

![2d908cda56bc729673d12f919071037ccdd56b6b](https://user-images.githubusercontent.com/6666082/136676691-c9da683b-18fd-412b-9e40-efc83c45908a.png
)

Attempted all permutations of installing and reinstalling both keymaster and configs for both locks getting the same consistent errors above.

**Comment by dadcoachengineer** [comment]
Note that I found a workable solution in downgrading to 0.63, setting up parent/child locks, then upgrading to 0.72. There are likely a few issues with the config scripts in 0.7x that were not present in previous builds.

**Comment by firstof9** [comment]
Fixed with #241
