### ISSUE TITLE
ISSUE: TypeError: string indices must be integers

### ISSUE THREAD

**Issue by pkg40** [FutureTense/keymaster#240]
**Describe the bug**

When adding integration for my 2nd schlage zwave connect lock, integration does not complete. I do get the slot entities requested and network entity. No package/keymaster/lockname/xxx directory or yaml files generated. After reboot error tag on integration disappears, but none of the entities that would be generated by yaml are there.

**Environment (please complete the following information):**

- OS: Ubuntu 20.041 
- NUC
- Home Assistant version: [core-2021.10.4]
- Supervised installation
- Component version: [0.0.74]
- Z-Wave integration name: [zwave_js]
- Lock make and model: [Schlage BE469]

**Logs**
General
Server Controls
Logs
Info
Watchdog heartbeat timeout:

2:51:59 PM – (WARNING) /usr/local/lib/python3.9/site-packages/bellows/zigbee/application.py
Error setting up entry frontdoor for keymaster
2:51:29 PM – (ERROR) keymaster (custom integration)
Error handling request
2:51:04 PM – (ERROR) /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py

**Screenshots**
![image](https://user-images.githubusercontent.com/12990477/137402028-473f40c3-da0a-4445-967d-803b6d4efc0b.png)

**Additional context**
no notifications generated.

**Comment by r0okey** [comment]
I have the very same issue when trying to add a second lock but in my case they are kwikset locks. Is there a fix for this?

**Comment by firstof9** [comment]
Need more info, is there a traceback in the log file?

**Comment by pkg40** [comment]
Unfortunately no. The full log message is in original post. This is with log level set to debug per instruction in readme. Is there a persistent flag set somewhere to  trigger or inhibit the code which generates yaml files? Is there a manual means to run the generation script? My stopgap solution was to copy yaml from first log and globally substitute lock name. This worked to allow manually setting up page to manage lock, but I think some bits that would be there to manage transfer of info from parent are missing.

**Comment by r0okey** [comment]
<img width="635" alt="Capture" src="https://user-images.githubusercontent.com/41972140/137640478-f22ead55-17f1-4d51-8ac0-0dcb12ab4339.PNG">

In my case, I see these error message in the system logs.

**Comment by pkg40** [comment]
aha, realized traceback was filtered out. Here is mine
config/custom_components/keymaster/
Logger: homeassistant.config_entries
Source: custom_components/keymaster/services.py:242
Integration: keymaster (documentation, issues)
First occurred: 3:00:41 PM (1 occurrences)
Last logged: 3:00:41 PM

Error setting up entry frontdoor for keymaster
Traceback (most recent call last):
```
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 304, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/keymaster/__init__.py", line 288, in async_setup_entry
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1491, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await self._hass.async_add_executor_job(handler.job.target, service_call)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/keymaster/__init__.py", line 264, in _generate_package
    generate_package_files(hass, name)
  File "/config/custom_components/keymaster/services.py", line 238, in generate_package_files
    config_entry = next(
  File "/config/custom_components/keymaster/services.py", line 242, in <genexpr>
    if hass.data[DOMAIN][entry_id][PRIMARY_LOCK].lock_name == name
TypeError: string indices must be integers
```

**Comment by r0okey** [comment]
> Unfortunately no. The full log message is in original post. This is with log level set to debug per instruction in readme. Is there a persistent flag set somewhere to trigger or inhibit the code which generates yaml files? Is there a manual means to run the generation script? My stopgap solution was to copy yaml from first log and globally substitute lock name. This worked to allow manually setting up page to manage lock, but I think some bits that would be there to manage transfer of info from parent are missing.

I also ended up manually creating all the yaml files one by one. It was
Extremely painful but at least it’s working with all my locks now. Thanks for the tip.

**Comment by firstof9** [comment]
@pkg40 is your 2nd lock added as a child lock?

**Comment by pkg40** [comment]
I have tried as child and not as child with same result

Sent from Yahoo Mail on Android 
 
  On Mon., 18 Oct. 2021 at 6:36 a.m., ***@***.***> wrote:   


@pkg40 is your 2nd lock added as a child lock?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pkg40** [comment]
Yes that fixed it for me. Will it go in next production release?

Sent from Yahoo Mail on Android 
 
  On Mon., 18 Oct. 2021 at 9:53 a.m., ***@***.***> wrote:   


Closed #240 via #241.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by firstof9** [comment]
Already released.

**Comment by rplankenhorn** [comment]
@firstof9 I am still seeing this exact same issue even with the latest version (0.0.76).  I double checked my entity names per these instructions:

```
Home Assistant Zwave keymaster package

N.B. After you add your devices (Zwave lock, door sensor) to your Z-Wave network via the inclusion mode, use the Home Assistant Entity Registry to rename each entity that belongs to the device and append _LOCKNAME to it. For example, if you are calling your lock FrontDoor, you will want to append _FrontDoor to each entity of the device.

sensor.schlage_allegion_be469_touchscreen_deadbolt_alarm_level
would become
sensor.schlage_allegion_be469_touchscreen_deadbolt_alarm_level_frontdoor

Do this step for each lock and door sensor.

This will automatically generate the keymaster files just as the setup.sh script would have.
```

But I am still having issues.  This is an example of how I have my entities named:
![Screen Shot 2021-10-26 at 11 19 26 AM](https://user-images.githubusercontent.com/228338/138909745-ac4a2964-e525-4e04-bcee-828d87106cf0.png)

Is it important to have the lock name at the end instead of the beginning of the entity?

**Comment by firstof9** [comment]
> Is it important to have the lock name at the end instead of the beginning of the entity?

No these are old instructions. All updated instructions are in the Wiki.



> I am still seeing this exact same issue even with the latest version (0.0.76).

Open a new issue and paste your log output in the issue.
