### ISSUE TITLE
ISSUE: After adding a lock to keymaster, I can no longer see data in the Home Assistant history page

### ISSUE THREAD

**Issue by BenBergman** [FutureTense/keymaster#245]
**Describe the bug**
After configuring a lock with keymaster, clicking the history page in Firefox on my desktop shows the date range at the top with a spinning loading icon where the data visualizations should be. It does not load. The mobile app behaves similarly.

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: RPi4, booting from USB3 hard drive (not SSD)
- Home Assistant version: core-2021.10.6
- Hassio/Docker/Core?: Core
- Component version: v0.0.76 (assuming this is the keymaster version)
- Z-Wave integration name: zwave_js
- Lock make and model: Yale Asure YRD216

**Logs**
No errors in the Supervisor -> System tab after a fresh HA restart and reloading the history page

**Screenshots**
![image](https://user-images.githubusercontent.com/142754/139305959-a11d54af-8a4b-48c1-ad02-384eb4d95163.png)

**Additional context**
I have deleted the keymaster integration for my lock and the issue persists (I still have the integration installed through HACS). I'm guessing the huge amount of entities for the lock is somehow overwhelming something, and they are persisting even though the entities have been removed.

**Comment by firstof9** [comment]
History loads fine here
![image](https://user-images.githubusercontent.com/1105672/139308784-f47d207c-833e-4c0f-ba19-8858223fdc18.png)

This isn't going to be an integration issue, how many code slots did you configure?

**Comment by BenBergman** [comment]
I figure it is probably an issue with setup and not an integration bug, but
it started when I added this integration so thought I'd check here for help.

I left it at the default 10 slots at first, then dropped it down to 5. If
setting it too high can cause these issues, a lower default might be good?

**Comment by firstof9** [comment]
Code slots don't cause issues, they just add additional entities. I could see this being an issue if you had added say 50+ code slots, but not 5-10.

**Comment by BenBergman** [comment]
Closing this issue. I reinstalled HA on an external hard drive instead of an SD card and I'm not having the history page issues any more (at least no lock ups - it still loads very slowly due to all the entities in keymaster).

**Comment by raman325** [comment]
The reason that this comes up is become of the number of entities we add which is pretty huge - logbook can't keep up on underpowered systems. Good motivation to reduce it if/where possible

**Comment by BenBergman** [comment]
Yeah, the number of entities is pretty nuts. It would be nice if there was a way in HA to flag entities and automations from add-ons so they can be hidden from normal view. It seems like I have 100x more entities and automations from keymaster than I do from everything else. Maybe the entity categorization introduced in 2021.11 could be useful here: https://www.home-assistant.io/blog/2021/11/03/release-202111/#entity-categorization

I'll open a new ticket for this.
