### ISSUE TITLE
ISSUE: Keymaster doesn’t show all available locks

### ISSUE THREAD

**Issue by anikkar** [FutureTense/keymaster#253]
**Describe the bug**
I’ve got Keymaster setup (using zwavejs2mqtt) and I’ve been able to successfully add 2 of my 4 locks (there are some bugs, but it’s working overall)

However, when I go to add the other ones, they don’t show up in the dropdown, but they are listed in the devices in HA.

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: Synology w/ Docker
- Home Assistant version: [e.g. 0.105.5]
- Hassio/Docker/Core? Docker
- Component version: [e.g. 0.1.2]
- Z-Wave integration name: zwavejs2mqtt
- Lock make and model: Yale Assure SL

**Logs**
Paste your error logs here.

**Screenshots**
<img width="1789" alt="Screen Shot 2021-11-11 at 8 59 17 PM" src="https://user-images.githubusercontent.com/80649/141738972-206ce1d7-c98c-4c27-9c17-100ed2fb3b3e.png">
<img width="574" alt="Screen Shot 2021-11-11 at 8 59 34 PM" src="https://user-images.githubusercontent.com/80649/141738976-47c67a4a-5420-4d11-be34-4a71cad2ccc4.png">

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Check your entity names in the `zwavejs` integration.

**Comment by anikkar** [comment]
Thanks for the tip...they were misnamed.
