### ISSUE TITLE
ISSUE: Kwikset 910 Z-Wave - Pin won't set with 'device_id' and 'domain' defined in action/sequence

### ISSUE THREAD

**Issue by gwhitlock8** [FutureTense/keymaster#258]
**Describe the bug**
I currently have 3 Kwikset 910 Smart locks installed and am using ZWaveJS to manage them in my HASSIO instance (RPi). When I initially installed and setup Keymaster, the codes that we being set/enabled within the lovelace dashboard would not carry over to the zwave_js config (i.e., they weren't actually registering with zwave_js and thus not actually being saved to the lock configuration). However, after adding in the `device_id` and `domain` to the code configuration yaml (in this case, _/config/packages/keymaster/backdoor/backdoor_keymaster_1.yaml_), setting the code via the lovelace dashboard worked flawlessly. 

Thus, my request is to have those key, value pairs automatically added to the config file. Please let me know if any additional information is needed. Thank you!

![image](https://user-images.githubusercontent.com/22160426/145842195-30857660-6603-4b87-a124-8c3e76d4c303.png)

**Environment (please complete the following information):**

- OS: HASS OS
- Type of system that HA is running on: RPi4
- Home Assistant version: core-2021.11.5
- Component version: v0.0.77
- Z-Wave integration name: zwave_js
- Lock make and model: Kwiskset 910

**Comment by firstof9** [comment]
Please do not post images of text.

**Comment by firstof9** [comment]
Also note the `device_id` and `domain` information is not used with the `add_code` service call so it gets removed.

**Comment by gwhitlock8** [comment]
@firstof9 - apologies for posting the image. And you're right, it worked without those fields. I'm not sure why I was seeing that issue to begin with. Closing issue
