### ISSUE TITLE
[Feature Request] Tie codes to User entities instead of locks

### ISSUE THREAD

**Issue by johnschieferleuhlenbrock** [FutureTense/keymaster#259]
**Is your feature request related to a problem? Please describe.**
Managing codes is slot-specific, not user-specific.

**Describe the solution you'd like**
Instead of managing each lock individually, or with parent-child relationships, it would be great if the user entities could be extended with their specific configurations and then associated with specific locks.

**Comment by firstof9** [comment]
I'm almost certain this would require some type of expansion of the `person` integration in Home Assistant core.

**Comment by johnschieferleuhlenbrock** [comment]
Quite possible, but I think the benefit would be great if we could help guide that integration. Anyway, just a thought.
