### ISSUE TITLE
"Notification Example Script" wiki page needs updating

### ISSUE THREAD

**Issue by kbarnes3** [FutureTense/keymaster#260]
**Describe the bug**
The wiki page on [Notification Example Script](https://github.com/FutureTense/keymaster/wiki/Notification-Example-Script) still shows the name of the script should be `<doorname>_manual_notify`, but this changed with version 0.56. The new script name should be `keymaster_<doorname>_manual_notify`.

**Comment by firstof9** [comment]
Fixed, thanks!
