### ISSUE TITLE
[Feature Request]   Buy Devs a Beer Button

### ISSUE THREAD

**Issue by dkebler** [FutureTense/keymaster#261]
This isn't a huge repo/project but it's done very well with attention to detail and what a user might really want (like supplying the lovelace UI yaml!).  And on top of that it's in rare company, a piece of code that just works without issues without install struggle.

Got a paypal donation button,  paypal email or use donations via Github (as long as you accept paypa)l?  I would like to make a modest donation, maybe others will too.  I pretty much make it my policy to spread a little weath to devs whose code I end up depending on and this is going to be used on a community building where we need to make codes in the exact ways this software allows.

**Comment by firstof9** [comment]
If I recall @FutureTense already discussed. I'll let him respond.
