### ISSUE TITLE
[Feature Request] Would like for the codes slots to work!

### ISSUE THREAD

**Issue by PaulR1001** [FutureTense/keymaster#262]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by firstof9** [comment]
Going to need more details.

**Comment by PaulR1001** [comment]
There are 10 user code slots available but no display of their contents or any way to change them. The lock / unlock seems to work fine but being able to assign user codes and delete them would be a good update.  I have not considered any other alternatives. I had MiCassa Verde controller years ago that would allow the user codes to be viewed and changed.

**Comment by PaulR1001** [comment]
I suppose it might be helpful for the type of lock I am using, it is a SCHLAGE model FE599. I am running Home Assistant latest version as of 3-4-2022 and have all the latest updates for ZWave js installed. Running on a Odroid 2n. Using the Nortek Z-Wave combo stick. Thanks Paul

**Comment by raman325** [comment]
@PaulR1001 do you use zwavejs2mqtt? if so can you see the user codes in that UI? Can you also share a screenshot of your keymaster UI? Finally, are you on the latest keymaster version?

**Comment by firstof9** [comment]
Note: The FE599 like the BE469 will only display `*`s in zwavejs2mqtt.
