### ISSUE TITLE
ISSUE: input_boolean showing up

### ISSUE THREAD

**Issue by jprokopowich** [FutureTense/keymaster#263]
**Describe the bug**
After following the installation via HACS and getting it working I noticed this in the "packages/keymaster/frontdoor/frontdoor_lovelace"
      - input_boolean.frontdoor_garageacess_notifications

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: RPi3
- Home Assistant version: 2021.12.10
- Hassio/Docker/Core?
- Component version: v0.0.77
- Z-Wave integration name: zwave_js
- Lock make and model: Kwikset 910
- 
**Logs**
NA

**Screenshots**
NA

**Additional context**
I do have garage door controllers setup with HA but nothing resembles garageacess.

**Comment by RyanWor** [comment]
I too am curious what the purpose of this input_boolean is. 

Environment (please complete the following information):

OS: HassOS
Type of system that HA is running on: RPi4-8gb
Home Assistant version: 2022.3.5 
Hassio/Docker/Core? 
Component version: v0.0.76
Z-Wave integration name: zwave_js
Lock make and model: Kwikset 620

**Comment by WS-Dave** [comment]
+1
experiencing the same issue.

Describe the bug
In the 'badge section' of the auto-generated 'kwikset_basement_lovelace' files, there is what appears to be a strange entry on line 10

  - input_boolean.LOCKNAME_garageacess_notifications
Regardless of the name or function of the lock (I have several Kwikset units) - that line (referencing garageaccess_notifications) is always there.

This seems like a potential bug - or (if not...) what is it intended to show for each lock?

There are matching entities for each lock - but I can't figure out what it is supposed to indicate.

Thx!

**Comment by firstof9** [comment]
You're referring to this line:

https://github.com/FutureTense/keymaster/blob/9e931b35cf8d875d713e02cb9b6897dc9855ce04/custom_components/keymaster/lovelace.head#L9

That'd be leftover code from an older iteration. You can remove the line.
