### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by dotnetslash** [FutureTense/keymaster#264]
**Is your feature request related to a problem? Please describe.**

Switching from home assistant in a virtualenv to haos and keymaster doesn't show up in the Add-on store. (It still shows up the virtualenv)

**Describe the solution you'd like**
Get it in the Add-on store (or tell me what I pooched.)

**Describe alternatives you've considered**
I guess go back to manually calingl services

**Additional context**
I got nothin' TBH I'm a command-line bigot and all this magic gui stuff is a mystery to me. If there's anything else you need let me know

**Comment by dotnetslash** [comment]
I just found the [Create an add-on repository](https://developers.home-assistant.io/docs/add-ons/repository/) doc.

It looks like if you add a `repository.yaml` in the git root we can add it with the git url.

**Comment by raman325** [comment]
You are looking in the wrong place. Keymaster is an integration, not an add on. Please re-read the README and look up HACS

**Comment by dotnetslash** [comment]
Doh! I thought I had HACS installed but I didn't.

Thanks (and sorry).
