### ISSUE TITLE
[Feature Request] Categorize keymaster entities as diagnostic to reduce clutter

### ISSUE THREAD

**Issue by BenBergman** [FutureTense/keymaster#265]
**Is your feature request related to a problem? Please describe.**
When viewing the history tab, using the default dashbord, or browsing through entities and automations, the large number of entries from keymaster can make it difficult to find the items the user actually cares about.

**Describe the solution you'd like**
Anything that is used by keymaster under the hood and not intended for direct use by the user should be hidden away. HA probably doesn't have a great way to do this yet, but the entity categorization introduced in 2021.11 may be a good first step (https://www.home-assistant.io/blog/2021/11/03/release-202111/#entity-categorization)

**Comment by BinaryShrub** [comment]
This would be great, so much clutter from Key master.

**Comment by jeffphilly** [comment]
yes, keymaster is amazing, but i could really use a clean up of all the helpers in the UI!

**Comment by pbye** [comment]
Maybe take advantage of the new hidden status on entities in 2022.4

**Comment by jeffphilly** [comment]
I tried the hidden status, but it does not remove them from the helpers section...perhaps i am doing something wrong

**Comment by raman325** [comment]
we unfortunately can't take advantage of any of these features because they require the entity registry which the entities we create don't support. I get that the number of entities generated is annoying, but it's the simplest way to solve the problem that keymaster tries to solve. I at one point tried to reduce the number of entities significantly, and I hit som cases where things wouldn't work and I couldn't resolve them so I gave up. I may try again in the future, but for now, this is just something we have to live with 🤷🏾

**Comment by fireheadman** [comment]
something I have noticed while troubleshooting is when I had to start over (remove a lock) from keymaster, it left behind the scripts and helps.  I just realized this and now have a mess to clean up from lingering (old) items.

**Comment by elwing00** [comment]
Can we use the new schedule helper to at least remove the input_datetimes (https://www.home-assistant.io/integrations/schedule/)

**Comment by tykeal** [comment]
NOTE: I'm not one of the primary devs here just speaking from what I know of how things are currently structured:

It might be possible for the custom weekday configuration, which could potentially reduce the count of input_datetime entities by 13 entities per slot (14 datetime -> 1 schedule). The date range would still need to be kept as the schedule helper doesn't do date ranges, which I personally heavily use ;)

You would lose minute granularity and could only do 30 minute blocks if transitioned. Though I have a hard time knowing why someone would want something less than 30 minutes for a lock schedule.
