### ISSUE TITLE
Support locks through zwavejs2mqtt [Feature Request] 

### ISSUE THREAD

**Issue by segfaultex** [FutureTense/keymaster#266]
**Is your feature request related to a problem? Please describe.**
Doesn't work through mqtt which is a common solution to running HA in a container/remote from the zwave dongle.

**Describe the solution you'd like**
To be able to control the lock when added through mqtt.

Is this a possibility?

**Comment by firstof9** [comment]
What do your MQTT calls look like for setting user codes?

**Comment by segfaultex** [comment]
I don't know if the usercode zwave ids are specific per device
You publish to the topic.
(subscribed topics can be found from the lock device entity MQTT INFO)

Set the code to available
mqtt topic: zwave/nodeID_16/99/0/userIdStatus/1/set
```json
{
  "value": "0"
}
```
![image](https://user-images.githubusercontent.com/3958108/151065001-0c476498-8e1b-46d5-940e-4b87b542ae6f.png)



mqtt topic: zwave/nodeID_16/99/0/userCode/1/set
Set user code 1 to 123456
```json
{
  "value": "123456"
}
```
![image](https://user-images.githubusercontent.com/3958108/151065144-e65caa4f-6f46-483d-9fc0-e310e879c347.png)

**Comment by raman325** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Doesn't work through mqtt which is a common solution to running HA in a container/remote from the zwave dongle.
> 
> 
> 
> **Describe the solution you'd like**
> 
> To be able to control the lock when added through mqtt.
> 
> 
> 
> Is this a possibility?

Can you qualify that this is a common solution? Analytics tell a different story.

**Comment by blueharford** [comment]
Is there any plan on supporting this? It’s a much more simple integration for zwave
