### ISSUE TITLE
ISSUE: Keymaster Notifications

### ISSUE THREAD

**Issue by jeprice77** [FutureTense/keymaster#268]
Since the websocket change for notifications,  i am no longer getting the keymaster push notifications. 
 I used to get a notification telling me who opened the lock  when using keypad.  Perhaps it's related to something else but i noticed the issue when home assistant changed to the notification websocket just recently.  I am getting other notifications from home assistant just not the keymaster ones.

UPDATE:   REMOVED INTEGRATION AND REINSTALLED.  NOW IT WORKS AGAIN, NOT SURE WHY IT STOPPED BUT ALL GOOD NOW.  PROBLEM SOLVED

**Comment by firstof9** [comment]
I am unable to duplicate this issue, my notifications are working fine.
