### ISSUE TITLE
New install for Keymaster [binary_sensor.fake missing]

### ISSUE THREAD

**Issue by fireheadman** [FutureTense/keymaster#280]
**Describe the bug**
noticed the binary_sensor.fake is missing

**Environment (please complete the following information):**
![image](https://user-images.githubusercontent.com/19847195/169958286-9e1b4adf-f5d1-4eeb-8e43-cdd09533c5e1.png)

- OS: [e.g. HassOS/Raspbian/CentOS]
- Type of system that HA is running on: [e.g. RPi3/NUC/Synology]
```
HA Rig:
OS: Debian 10 w/Docker
MOBO: Intel DQ77KB
CPU: i5-3470T@ 2.90GHz w/Silverstone NT07-115X
RAM: 4GB DDR3 1333Mhz
SSD: LiteOn 64GB mSata
NIC: Intel I350-T2
CASE: iStarUSA D-118V2-ITX w/Noctura fans

```
- Hassio/Docker/Core? docker
- Component version: [e.g. 0.1.2]
- Z-Wave integration name: [e.g. zwave_js] zwaveJS
- Lock make and model: [e.g. Schlage BE469] 
BE469ZP / FE599

**Logs**
Paste your error logs here.

**Screenshots**
![image](https://user-images.githubusercontent.com/19847195/169958119-2b96ed2a-57bc-4aa3-92a0-387bee1289cf.png)

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by fireheadman** [comment]
![image](https://user-images.githubusercontent.com/19847195/169958717-7f7a9a05-fb00-4b25-99d9-2b36c2062342.png)


Unsure if this is to be installed by keymaster or I need to install this sensor manually?
Please advise.

**Comment by firstof9** [comment]
It doesn't actually exist. You can remove that entry on your dashboard as it's a place holder for an actual door sensor.

**Comment by fireheadman** [comment]
ok thanks...  may end up getting a few door sensors to fill this in
