### ISSUE TITLE
Auto lock timer automation locks door even when open

### ISSUE THREAD

**Issue by alsoszaa** [FutureTense/keymaster#283]
I use a sensor on my door to determine the open/closed status of the door. When I open my door and keep it open, the door lock still counts down and the lock engages even though its open. 
Then sometimes I close my door and the timer engages, and I open my door before the timer ends and the lock engages when the door is open. 
There must be a way to have a condition for the timer to only engage the lock if the door sensor sees the door as closed. Right now it doesn't do this and we forget it does this and the bolt hits the door siding leaving dents.

**Comment by grmocg** [comment]
same.

**Comment by grmocg** [comment]
This was a bit surprising when there were door sensors configured. Without door sensors, this was unsurprising.
