### ISSUE TITLE
Wrong operand in keymaster_common

### ISSUE THREAD

**Issue by hkhard** [FutureTense/keymaster#286]
Hi,

I think day/night evaluation miscalculates. I changed line 114 from:

            {% if (((as_timestamp(states.sun.sun.attributes.next_dusk)) > (as_timestamp(states.sun.sun.attributes.next_dawn)))) %}
to

            {% if (((as_timestamp(states.sun.sun.attributes.next_dusk)) < (as_timestamp(states.sun.sun.attributes.next_dawn)))) %}

this seems to work for me.

**Comment by hkhard** [comment]
Keymaster 0.80
Home Assistant Core 2022.6.5
Home Assistant Supervisor 2022.05.3
Home Assistant OS 7.3

**Comment by firstof9** [comment]
Feel free to drop a PR with the changes :+1:

**Comment by hkhard** [comment]
👍
PR sent, was wrong about the operand. Submitted with clearer and working code for my environment.

**Comment by hkhard** [comment]
as above.
