### ISSUE TITLE
ISSUE: Lovelace installation is not accurate for 2022.7.x

### ISSUE THREAD

**Issue by alekline** [FutureTense/keymaster#289]
**Describe the bug**
The steps to configure the UI give in https://github.com/FutureTense/keymaster/wiki/Lovelace-View are not accurate for 2022.7.x

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: RPi4
- Home Assistant version: 2022.7.6

**Additional context**
There is no option called "Configure UI" or LoveLace editor

**Comment by firstof9** [comment]
Wiki updated.
