### ISSUE TITLE
ISSUE: Since updating to the latest zwavejs2mqtt in HA, keymaster no longer finds it

### ISSUE THREAD

**Issue by jds11111** [FutureTense/keymaster#290]
**Describe the bug**
Since the update, I now get this error message in my logs:
```
This error originated from a custom integration.

Logger: custom_components.keymaster.binary_sensor
Source: custom_components/keymaster/binary_sensor.py:49
Integration: keymaster (documentation, issues)
First occurred: 10:19:02 AM (8 occurrences)
Last logged: 10:21:53 AM

Z-Wave integration not found
```

**Environment (please complete the following information):**

- OS: Home Assistant OS 8.4
- Type of system that HA is running on: RPi4B
- Home Assistant version: core-2022.7.7
- Component version: v0.0.82 
- Z-Wave integration name:zwavejs2m1tt
- Lock make and model: Schlage BE469

**Logs**
```
This error originated from a custom integration.

Logger: custom_components.keymaster.binary_sensor
Source: custom_components/keymaster/binary_sensor.py:49
Integration: keymaster (documentation, issues)
First occurred: 10:19:02 AM (8 occurrences)
Last logged: 10:21:53 AM

Z-Wave integration not found
```

**Screenshots**
none

**Additional context**
Only noticed the logs today, after the update earlier today.

**Comment by jds11111** [comment]
Really?  No one else has this problem?  It is not allowing me to add or delete codes. Stopped sending notifications.

**Comment by firstof9** [comment]
The zwavejs integration is loaded?

**Comment by jds11111** [comment]
Yeah. And I reloaded both integrations. All zwave entities are connected and working. I gave up, deleted one of the keymaster integrations and started over. It works now, but the other one is still problematic.
