### ISSUE TITLE
Unable to get keymater to update PINs

### ISSUE THREAD

**Issue by mtwalkup** [FutureTense/keymaster#292]
I hesitate to even make this bug report because I am so new to HA, but here we go.

HA OS on a Raspberry Pi:
Home Assistant 2022.8.1
Supervisor 2022.8.2
Operating System 8.4
Frontend 20220802.0 - latest
Z-Wave JS (only Z-Wave add-on used) 0.1.65
Lock: BE469 (says by Allegion, but it is a Schlage lock)
Device Status: Alive
Device Ready: Yes
Highest Security: S0 Legacy
Z-Wave Plus: No
Keymaster Version 0.0.82
Installed via HACS

I can lock/unlock via HA UI without issue.  I have enabled debug logging for Z-Wave JS and KeyMaster.

Z-Wave JS does nothing when I try to set a pin.

I don't see anything in the KeyMaster log either.

I only see this log entry related to Keymaster:
2022-08-06 21:27:26.001 DEBUG (MainThread) [custom_components.keymaster] Finished fetching keymaster data in 0.000 seconds (success: True)
2022-08-06 21:27:31.001 DEBUG (MainThread) [custom_components.keymaster] Finished fetching keymaster data in 0.000 seconds (success: True)

Even the auto-lock seems to work which I think comes from Keymaster?

But I try to change a PIN Code (add or remove) and it just says PIN Status: adding or deleting.  No log changes to Keymaster log (even with debug) and no changes to z-wave js (even with silly mode).

Network entity shows Connected.  Allow automation is on.

I was having the same issue and decided to try nuking it (remove integration, remove all related entities I could find, exclude lock from z-wave, factory reset lock, include lock in z-wave [forcing legacy secure], add integration again).  Still, same results.

I have two of the locks, I experienced the same problem with both prior to nuke.  I am just testing with one lock now.  I was using Smartthings previously and it was working fine.

**Comment by firstof9** [comment]
Likely your usercodes command class isn't populated.
You'll need to re-interview your lock until the usercodes command class populates.

**Comment by mtwalkup** [comment]
@firstof9 you’re right. Re-interviewing the device a couple of times seems to have resolved the issue.

**Comment by mtwalkup** [comment]
Fixed.

**Comment by mtwalkup** [comment]
Fixed
