### ISSUE TITLE
ISSUE: Manual Install help?

### ISSUE THREAD

**Issue by arpitgupta** [FutureTense/keymaster#293]
Not sure if this is the best way to get support. If there are other channels please let me know. I dont have hacs and was wondering for manual install if i just `custom_components/keymaster` dir to `ha_conf_dir/custom_compoents`?

I think that is how i should set it up, but am not 100% sure. Dont run a lot of custom integrations.

**Comment by firstof9** [comment]
> for manual install if i just `custom_components/keymaster` dir to `ha_conf_dir/custom_compoents`?

Yes

> If there are other channels please let me know.

There's an extensive thread on the HA forums.

**Comment by arpitgupta** [comment]
Thanks, i should have paid more attention to the info. I jumped straight to install.

Would it be ok to submit a PR to add appropriate info to the install section of the wiki?

**Comment by arpitgupta** [comment]
I cant quite figure out how to send a PR to wiki repo. This was the change I was thinking

```
diff --git a/Install-the-integration.md b/Install-the-integration.md
index 2a361a5..712fc81 100644
--- a/Install-the-integration.md
+++ b/Install-the-integration.md
@@ -2,6 +2,8 @@
 
 This integration can be added to your installation manually, but the *supported* method requires you to use The [Home Assistant Community Store](https
://community.home-assistant.io/t/custom-component-hacs/121727).  If you dont't already have HACS, it is [simple to install](https://hacs.xyz/docs/insta
llation/prerequisites).
 
+For manual install you need to copy directory `custom_components` or `custom_components/keymaster` to your Home Assistant config dir so that
 the following path `HOME_ASSISTANT_CONF_DIR/custom_components/keymaster` exits. Now restart Home Assistant so that integration is loaded.
+
 Open HACS and select the Integrations tab.  Click the + icon at the bottom right and search for `keymaster`.  You will then get a message that the int
egration requires Home Assistant to be restarted.  Please do so.
 
 You need to create an integration for each lock you want to control.  Select Configuration | Integrations.  Click the + icon at the bottom right and s
earch for **keymaster** and select it.
@@ -53,4 +55,4 @@ This sensor returns the command number just executed by the lock.  Schlage value
 
 #### 9.  **Path to packages directory**
 
-The default `packages/keymaster` should suffice.
\ No newline at end of file
+The default `packages/keymaster` should suffice.
```

**Comment by firstof9** [comment]
HACS is the perfered method as it 1) easier to use and 2) makes updating simple with handy notifications when updates are published.

**Comment by arpitgupta** [comment]
Agree 100% on that. I was under the wrong impression that hacs would only work with supervisor install. I now see it can be setup for docker container as well. BTW the simple to install link in the readme leads to a 404. New link is: https://hacs.xyz/docs/setup/prerequisites

**Comment by firstof9** [comment]
Thank you! I'll update the link.
