### ISSUE TITLE
Log error "keymaster_back_door_lock Lock Notifications: Already running"

### ISSUE THREAD

**Issue by Anto79-ops** [FutureTense/keymaster#294]
Hi,

Great integration! 

I have a few Kwikset 910 locks. For one of the locks, everytime there is an event for the lock, I get this log error.

```
Logger: homeassistant.components.automation.keymaster_back_door_lock_lock_notifications
Source: helpers/script.py:1442
Integration: Automation (documentation, issues)
First occurred: 8:45:30 AM (2 occurrences)
Last logged: 10:05:12 AM

keymaster_back_door_lock Lock Notifications: Already running
```

If I turn off the notifications for this lock, the error stops logging it.

Not sure why this lock is doing it, but the other 2 locks (which are the same), are not doing this.

here is the lock in question.

![image](https://user-images.githubusercontent.com/79593761/186208180-d53f6414-44c1-4b31-82cb-12ed8098eff3.png)

- HAOS
- RPi4
- Home Assistant version: 2022.8.6
- Component version: v0.0.82
- Z-Wave integration name: zwavejs2mqtt
- Lock make and model: Kwikset 910 X3

**Comment by Anto79-ops** [comment]
Here's some more information, it seems like the notification gets triggered twice. For example, here is the first notification trace, notice the time started at 1:20:06 pm and done at 1:20:07 pm

![image](https://user-images.githubusercontent.com/79593761/186257452-15be27ff-02a6-4cf2-9ae8-cbb06a8697ad.png)

then, if I toggle to the right for the next trace:

![image](https://user-images.githubusercontent.com/79593761/186257704-66302f34-5c31-4992-92d4-db86a5297633.png)

it fires again, at the some time 1:20:06 pm ,  but it doesn't execute because of the single execution rule.

Any idea why this one if firing twice at the trigger?

Here is the entire automation:

![image](https://user-images.githubusercontent.com/79593761/186258194-e43043b5-4688-44d7-85ae-b577fc389bdc.png)

**Comment by Anto79-ops** [comment]
ok the plot thickens....it seems my lock is sending CC command twice.... that weird, right?

![image](https://user-images.githubusercontent.com/79593761/186259462-09c597e9-9dca-4159-a710-953d48f95b2a.png)

**Comment by firstof9** [comment]
Ignore the logger warning, that's the best way to handle this.

**Comment by Anto79-ops** [comment]
Lol I will, but I'm going to try one more thing, my back lock is the furthest away from everything, I got  a few repeaters coming in tomorrow to help the network. 

Going to exclude and include the lock and try again.... "It's not your code it's the lock" that must be a saying to use, anytime you use zwave locks...hehe
