### ISSUE TITLE
ISSUE:  Unkown service

### ISSUE THREAD

**Issue by ingo916** [FutureTense/keymaster#295]
**Describe the bug**
After upgrading to HA 2022.9.0 I get the following message, see screenshot

**Environment (please complete the following information):**

 Home Assistant 2022.9.0
Supervisor 2022.08.5
Operating System 8.5
Frontend 20220907.0 - latest 

**Logs**
Paste your error logs here.

**Screenshots**
![image](https://user-images.githubusercontent.com/41309095/189027303-7e5c54c4-9eab-470e-a467-a1b900364b4a.png)

**Additional context**

**Comment by firstof9** [comment]
Means you didn't create the notification script, safe to ignore.

**Comment by ingo916** [comment]
How do I generate the script to prevent the error message coming back

**Comment by firstof9** [comment]
Check [here](https://github.com/FutureTense/keymaster/wiki/Notification-Example-Script#example-notification-script) in the wiki.

**Comment by dcerny1** [comment]
> Means you didn't create the notification script, safe to ignore.

Why would I have needed to create the script? Keymaster is a package that the user doesn't update. What changed in 2022.9.0 to cause this error?

**Comment by Alethio36** [comment]
i had the same issue, i rolled back and that fixed the issue, after a few days, i just tried again and worked perfectly.

**Comment by firstof9** [comment]
> Why would I have needed to create the script?

Because we don't know what notification systems you've configured.



> What changed in 2022.9.0 to cause this error?

It's not an error it's a warning.

**Comment by dcerny1** [comment]
> > Why would I have needed to create the script?
> 
> Because we don't know what notification systems you've configured.
> 
> > What changed in 2022.9.0 to cause this error?
> 
> It's not an error it's a warning.

Thanks for your response. I understand that you don't know what I configured, but I didn't make any changes and all of a sudden this warning has appeared. So something must have changed somewhere outside of my control to cause it.  I didn't have a script before the change and all was well. Suddenly the warnings started. I created a dummy script to handle the issue.

**Comment by csanner** [comment]
> > > Why would I have needed to create the script?
> > 
> > 
> > Because we don't know what notification systems you've configured.
> > > What changed in 2022.9.0 to cause this error?
> > 
> > 
> > It's not an error it's a warning.
> 
> Thanks for your response. I understand that you don't know what I configured, but I didn't make any changes and all of a sudden this warning has appeared. So something must have changed somewhere outside of my control to cause it. I didn't have a script before the change and all was well. Suddenly the warnings started. I created a dummy script to handle the issue.

the thing that changed is that HomeAssistant now actively looks for these things and warns you. You didn't get a warning before because there were none, not because this was *working*.

I'm having a bit of an issue creating the script...I copy/pasted the yaml from that page into the "my scripts" page but I'm getting "Message malformed: extra keys not allowed @ data['keymaster_yale_lock_manual_notify']"

**Comment by alexruffell** [comment]
@firstof9 Is there any way to just disable the notifications functionality in keymaster or is there some YAML I can put in the script it seeks that simply does nothing but quiets the issue hunter? I never used scripted notifications (I do everything in Node Red) but now that HA actively reports issues, such as this, it won't stop alerting me to the issue. Selecting "submit" on the error message as if it were fixed doesn't do much as a day later it pops right back up.

**Comment by firstof9** [comment]
Add the script from the wiki, give it some benign service call.

**Comment by alexruffell** [comment]
@firstof9 I realized that one of my door codes had the "Notifications" switch turned on. Once I turned it off, given they are not even configured, the error never popped back up. Just leaving this comment in case it helps others in my same boat :)

**Comment by dcerny1** [comment]
All of my door codes have notifications turned on. I use these notifications for automation. If I turn them off, will I still be getting Keypad Unlock Operation, etc?

**Comment by csanner** [comment]
No but if they're working you shouldn't be getting this error?

**Comment by dcerny1** [comment]
I was getting this error only on manual notify. I created a dummy script to run when this notification happens and the error disappeared.

**Comment by CitizenRacer** [comment]
> I was getting this error only on manual notify. I created a dummy script to run when this notification happens and the error disappeared.

@dcerny1 can you provide some instructions for us on how to create the dummy script? I've tried using the example from the wiki but i'm clearly not doing something right.

Thank you!

**Comment by firstof9** [comment]
You could just disable the notifications as well per https://github.com/FutureTense/keymaster/issues/295#issuecomment-1252869632

**Comment by dcerny1** [comment]
I created a counter helper entity that I called “Fake Counter” just for this purpose and also created a script “keymaster_front_door_manual_notify” in scripts.yaml that does nothing other than reset this fake counter. I am sure that there are other ways to “do nothing”. With my limited coding skills (at least for HA), this is what I came up with.

 

keymaster_front_door_manual_notify:

  description: "To fix Keymaster_front_door User Notification uses an unknown service"

  mode: parallel

  sequence:

    - service: counter.reset

      data: {}

      entity_id: counter.fake_counter

 

Hope this helps.

 

David

**Comment by Alethio36** [comment]
for what its worth, i had some trouble with the script in the wiki, homeassistant didnt like that.

```
alias: keymaster_<yourdoornamehere>_manual_notify
sequence:
  - device_id: longstringofnonsensefromthedeviceid
    domain: lock
    entity_id: whateverlockyouwant
    type: unlock
  - service: whateverserviceyouwant
    data:
      message: "{{ message }}"
      title: "{{ title }}"
mode: parallel
icon: mdi:door-open
max: 10

```
works like a champ thus far. actually far better then i thought it would. the title and message in the script pulls from keymaster, very well done.

edit: formatting of the yaml code

**Comment by firstof9** [comment]
Also to be clear this isn't an error, it's a warning.
