### ISSUE TITLE
ISSUE: adding codes does not work for kwikset 910

### ISSUE THREAD

**Issue by kevincw01** [FutureTense/keymaster#300]
**Describe the bug**
When I add a code to any code slot and enable it, the pin status says "adding" forever.  I can lock and unlock the lock manually without issue.

**Environment (please complete the following information):**

- OS: HassOS 8.5
- Type of system that HA is running on:  RPi4 4gb
- Home Assistant version: 2022.9.4
- Hassio Supervisor 2022.08.6
- Component version: 0.0.8.2
- Z-Wave integration name: zwave_js
- Lock make and model: kwikset 910

**Logs**
Core:
```
2022-09-16 18:26:07.392 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration keymaster which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-09-16 18:26:07.395 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

zwave_jz:
```
2022-09-17T01:57:09.922Z CNTRLR   [Node 057] compat mapping found, treating V1 Alarm frame as Notification Repor
                                  t
2022-09-17T01:57:09.934Z CNTRLR   [Node 057] [Notification]
                                    type:   Access Control
                                    event:  Keypad lock operation
                                    userId: 0
2022-09-17T01:57:12.029Z CNTRLR   [Node 057] compat mapping found, treating V1 Alarm frame as Notification Repor
                                  t
2022-09-17T01:57:12.039Z CNTRLR   [Node 057] [Notification]
                                    type:  Access Control
                                    event: Manual unlock operation
```

**Screenshots**
<img width="1144" alt="ss" src="https://user-images.githubusercontent.com/455203/190838739-c9ac5e3c-8037-4ed5-88f2-b4b4cf953762.png">

**Additional context**
This lock was previously paired with a smartthings hub and the codes that were set by that integration still work.  I did properly exclude the device and include it on HA and I can lock and unlock it.  The codes I have not tried to set with keymaster say "deleting".

**Comment by kevincw01** [comment]
Doing some additional investigation, if in developer tools I look at the state of code slot 1-9, I see all the correct codes that were previously set by smart things.  This tells me that the lock was able to send the current codes to keymaster successfully.  Additionally, I can use the add code to lock keymaster service in developer tools to change one of the code slots to a new unique code and that works on the lock.  This tells me that keymaster can new codes to the lock successfully.  So it appears my issue is with the lovelace UI.  The lovelace ui came from the yaml file that was created upon install and i did a simple copy/paste so I'm not sure where to troubleshoot.

**Comment by TMarzullo** [comment]
I am having a similar issue: forever adding and deleting....For some of my unused slots, the code does seem to eventually get added as I tested it from the lock itself but the UI doesn't seem to reflect that. Additionally, my existing codes never pulled over. 

Even more odd, when I tried to add a subordinate lock (second keymaster instance) I get one of these for each slot:
![image](https://user-images.githubusercontent.com/8526092/194677201-164eae9a-f4c9-4818-b5c6-fded446a1298.png)

**Comment by kevincw01** [comment]
I gave up on key master and switched to "zwave js UI" add on in place of
standard zwave js.  2 key things it provides, 1) you at least have access
to a clunky UI to dorectly see/maintain codes if all else fails.  2) you
can turn on mqtt in the addon and get access to what codes are actually in
the lock after setting them so you know if it worked.  Then I built my own
basic Lovelace card and some loght automations to manage the codes in a
user friendly way.  It's working great and is reliablr but ofcourse is not
as advanced as keymaster.

**Comment by lotr** [comment]
@FutureTense maybe I've found the issue. I'm using danalock V3 Seems like there was a breaking change somewhere in the HA / ZWaveJS.

Your current implementation of `add_code`:

```
        servicedata[ATTR_ENTITY_ID] = entity_id
        await call_service(
            hass, ZWAVE_JS_DOMAIN, SERVICE_SET_LOCK_USERCODE, servicedata
        )
```

Seems like `SERVICE_SET_LOCK_USERCODE` just adds / registers the code.

You have to call something like `zwave_js.set_value` afterwards with attributes below to enable it

```
service: zwave_js.set_value
data:
  command_class: 99
  endpoint: 0
  property: userIdStatus
  property_key: <code slot number>
  value: 1 // this sets the status from available to enabled
target:
  device_id: <my device id>
```

**Comment by lotr** [comment]
This works:
```
async def add_code(
    hass: HomeAssistant, entity_id: str, code_slot: int, usercode: str
) -> None:
    """Set a user code."""
    _LOGGER.debug("Attempting to call set_usercode...")

    servicedata = {
        ATTR_CODE_SLOT: code_slot,
        ATTR_USER_CODE: usercode,
    }

    if async_using_zwave_js(
        entity_id=entity_id, ent_reg=async_get_entity_registry(hass)
    ):
        servicedata[ATTR_ENTITY_ID] = entity_id
        await call_service(
            hass, ZWAVE_JS_DOMAIN, SERVICE_SET_LOCK_USERCODE, servicedata
        )
        enable_code_service_data = {
            ATTR_ENTITY_ID: entity_id,
            "command_class": 99,
            "endpoint": 0,
            "property": "userIdStatus",
            "property_key": code_slot,
            "value": 1,
        }
        await call_service(
            hass, ZWAVE_JS_DOMAIN, "set_value", enable_code_service_data
        )
    else:
        raise ZWaveIntegrationNotConfiguredError
```

**Comment by firstof9** [comment]
That would be a bug in the `zwave_js` integration then as setting and clearing codes should also enable/disable the slot.

**Comment by kevincw01** [comment]
When I can call the zwave_js service it sets the enable for both of my 910
kwikset locks.

**Comment by lotr** [comment]
@firstof9 will you create a ticket in the integration github pages? Or should I do it?

**Comment by firstof9** [comment]
> @firstof9 will you create a ticket in the integration github pages? Or should I do it?

You're going to need driver logs to prove this is what's occurring, my 910 clears and sets codes fine.

**Comment by tykeal** [comment]
Mine clears and sets them fine too. Though I've noticed that occasionally it will get stuck with adding / deleting. Normally, when this happens I have to call the keymaster.set_code or keymaster.clear_code functions manually. What's more, is that sometimes it doesn't seem to actually take until I go change the log level of the zwave-js integration to debug level in the UI!

It's sorta weird.

**Comment by firstof9** [comment]
> What's more, is that sometimes it doesn't seem to actually take until I go change the log level of the zwave-js integration to debug level in the UI!

When you do this you're restarting the driver, same thing as restarting the container/addon.

**Comment by tykeal** [comment]
I don't think it's actually restarting the driver because I don't see anything in the logs on it rebuilding the mesh network like I do when the addon is restarted. I think it's much more like calling the logger.set_level service call to dynamically change the logging level.

**Comment by firstof9** [comment]
Changing the log level in zwavejs-ui reloads the driver.
Tail your logs then change the logging level, you'll see the driver reload.
