### ISSUE TITLE
Notification not working / manual notification scripts arnt there

### ISSUE THREAD

**Issue by dcf1999** [FutureTense/keymaster#301]
Just recently I’ve been getting errors that “ User Notifications uses an unknown service”. When I looked further into it, the manual notification script files are missing. It was all working fine not to long ago (was getting notifications). Is there a way to rebuild those scripts without having to re-install key master and re-program all the Locks? Any other ideas?

here is the actual error:

`The automation "keymaster_mudroom User Notifications" (automation.keymaster_mudroom_user_notifications) has an action that calls an unknown service: script.keymaster_mudroom_manual_notify.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](/config/automation/edit/keymaster_mudroom User Notifications) and remove the action that calls this service.

Click on SUBMIT below to confirm you have fixed this automation. `

**Comment by firstof9** [comment]
dupe #295
