### ISSUE TITLE
ISSUE: Missing script.keymaster_front_door_manual_notify

### ISSUE THREAD

**Issue by Gibby** [FutureTense/keymaster#302]
**Describe the bug**
Tried to run the `keymaster_front_door Reset` automation.

Received the following error.

```
keymaster_front_door Reset uses an unknown service
The automation "keymaster_front_door Reset" (automation.keymaster_front_door_reset) has an action that calls an unknown service: script.keymaster_front_door_manual_notify.

This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](/config/automation/edit/keymaster_front_door Reset) and remove the action that calls this service.

Click on SUBMIT below to confirm you have fixed this automation.
```

**Environment (please complete the following information):**

- OS: homeassistant/home-assistant:2022.9
- Type of system that HA is running on: Kubernetes
- Home Assistant version: 2022.9
- Hassio/Docker/Core? Docker
- Component version: v0.0.82
- Z-Wave integration name: zwave_js
- Lock make and model: BE469

**Additional context**

Looking under packages directory I do not see the script defined anywhere.

**Comment by firstof9** [comment]
Dupe #295
