### ISSUE TITLE
[Feature Request] Update to documentation

### ISSUE THREAD

**Issue by grosejon** [FutureTense/keymaster#306]
**Is your feature request related to a problem? Please describe.**
I want to know what the different notification badges at the top are for, and also whether auto locking is possible through keymaster. For example: if the door is closed for 30 seconds, lock it automatically.

**Describe the solution you'd like**
Add a short description in the wiki or on the forum explaining the Lock, Door, and Garage notifications. Also a short description of what the auto lock badges at the top do.

**Additional context**
![image](https://user-images.githubusercontent.com/36434630/200132584-307a98b9-f281-43a2-a113-817161f39a2d.png)

**Comment by TheTravelAddict** [comment]
I was just searching for the same info.  Please let me know if you find the answers (I am happy to edit the Wiki with the data if I had it)
