### ISSUE TITLE
Lovelace YAML error

### ISSUE THREAD

**Issue by thefjordkeeper** [FutureTense/keymaster#307]
Hi all,
Lovelace is giving me the following YAML error when I copy and paste the generated code in to a new dashboard:
"Your configuration is not valid: n: At path: views -- Expected an array value, but received: undefined"

The YAML passes all the major online validators and Visual Studio Code seemed okay with it, too.

Any ideas about what's going on?
[front_door_lovelace.txt](https://github.com/FutureTense/keymaster/files/9981350/front_door_lovelace.txt)

Thanks!

**Comment by tykeal** [comment]
Are you completely replacing the dashboard raw configuration with the generated YAML? I'm asking because the generated YAML is expected to go into the views section of an already defined dashboard.

```
views:
<generated_yaml>
```

**Comment by joeinaustin** [comment]
> Are you completely replacing the dashboard raw configuration with the generated YAML? I'm asking because the generated YAML is expected to go into the views section of an already defined dashboard.
> 
> ```
> views:
> <generated_yaml>
> ```

That is exactly the error I saw when I pasted yaml over, instead of under, the existing yaml.  I think tykeal nailed it.
