### ISSUE TITLE
Missing script: script.keymaster_backdoor_manual_notify

### ISSUE THREAD

**Issue by Kagey-cmd** [FutureTense/keymaster#312]
Receiving the following error from HASS, having made no recent changes:
> The automation "keymaster_backdoor User Notifications" (automation.keymaster_backdoor_user_notifications) has an action that calls an unknown service: script.keymaster_backdoor_manual_notify.
This error prevents the automation from running correctly. Maybe this service is no longer available, or perhaps a typo caused it.
To fix this error, [edit the automation](/config/automation/edit/keymaster_backdoor User Notifications) and remove the action that calls this service.
Click on SUBMIT below to confirm you have fixed this automation.

**Comment by firstof9** [comment]
dupelicate of #295
