### ISSUE TITLE
script.keymaster_LOCKNAME_manual_notify

### ISSUE THREAD

**Issue by SP410** [FutureTense/keymaster#314]
The service call: script.keymaster_LOCKNAME_manual_notify appears throughout the automations (locations below); however, the script is never instantiated.  What is the purpose of the script?  Can I set it up manually?

List of service calls:
[https://github.com/FutureTense/keymaster/search?q=script.keymaster_LOCKNAME_manual_notify]

**Comment by firstof9** [comment]
duplicate #295 

Please see the wiki.
