### ISSUE TITLE
ISSUE: Child locks do not seem to work...

### ISSUE THREAD

**Issue by dubhunter** [FutureTense/keymaster#319]
First, thanks for creating Keymaster. I have been using it for ~2 years (with a single lock on a different install).

I am running Keymaster 0.0.83, Z-Wave JS UI 1.5.0, and HA 2023.1.6.

I am trying to add 3 locks, 2 of them parents of the first. They are all Kwikset Home Connect 620s.

When I start adding the child locks, I get errors (like described in https://github.com/FutureTense/keymaster/issues/304).

The difference is that none of the child locks seem to be getting the pins.

**Comment by firstof9** [comment]
304 is a missing notification script as found [here in the wiki](https://github.com/FutureTense/keymaster/wiki/Notification-Example-Script#example-notification-script).

**Comment by asveikau** [comment]
Hi, I think this and #304 are a distinct issue from the missing notification script.  Note the 'not found' script in the error message is a different script than the notification one.

I just created the notifcation script, restarted HA and not fixed.

The script in the error message exists and shows up in HA's automations & scripts UI.  So it's weird that it's claimed not to exist.

**Comment by asveikau** [comment]
Found the bug and confirmed a fix locally.  Will open a PR.
