### ISSUE TITLE
[Feature Request] Add ability to select lock/unlock notifications

### ISSUE THREAD

**Issue by joeinaustin** [FutureTense/keymaster#328]
**When a lock is unlocked from the inside, no code is used, currently, it shows as a code unlock referencing that last code that was actually used.  That is a bug (see #327).  Once that is corrected, I would like the ability to choose if lock/unlock from the inside (no code) sends a notification.  I could think of a few more variations on this including the ability to checkbox each of the lock and unlock possibilties for notification.

lock w/o code
unlock w/o code
lock with code
unlock with code

The one unique case is lock w/o code.  These locks have the ability to choose if that is allowed.  IF that option is turned on at the lock, it allows you to lock the door from the inside or outside with NO code.  If the option is turned off (default), you must use a code to lock the door from the outside.

**Describe the solution you'd like**
If option selected, no notification is sent when no keypad code is actually entered.

**Describe alternatives you've considered**

**Additional context**

**Comment by firstof9** [comment]
> When a lock is unlocked from the inside, no code is used, currently, it shows as a code unlock referencing that last code that was actually used. That is a bug

Not a bug, your lock should update the `alarmLevel` value when this event occurs.



> I would like the ability to choose if lock/unlock from the inside (no code) sends a notification. I could think of a few more variations on this including the ability to checkbox each of the lock and unlock possibilties for notification.

This can be filtered out via the notification script.
