### ISSUE TITLE
Orphaned Lock Persisting Through Deleting/Reinstalling Integration

### ISSUE THREAD

**Issue by kars85** [FutureTense/keymaster#329]
I setup keymaster a couple of months ago, but wasn't dedicated to the time it was going to take to integrate properly. So, I deleted the integration and today reinstalled. A couple odd behaviors I'm hoping to get some insight on.

1) It appears that deleting the integration does not delete the dozens of entities that get created. Is this intentional or expected behavior?
![image](https://user-images.githubusercontent.com/6616548/220751773-354abd1b-92b1-4bcb-a594-2839d0a7a809.png)

2) The lock that I setup my first go round appears as an "orphaned" parent lock during re-installation of the integration. How can this orphaned device be deleted?
![image](https://user-images.githubusercontent.com/6616548/220751673-0e7645bb-08ab-454e-a348-35af66ddf689.png)

**Comment by firstof9** [comment]
> 1. Is this intentional or expected behavior?

Expected as you'd have to clear out the packages from the packages directory.



> 2\. The lock that I setup my first go round appears as an "orphaned" parent lock during re-installation of the integration. How can this orphaned device be deleted?

This happens when you don't actually remove the integration properly, you'll need to clear it from your `core.config_entries` manually while HA is shutdown.

**Comment by kars85** [comment]
Thanks @firstof9. 
1) Got it.

2) As you can probably tell, I just went to the HA integrations page and deleted the keymaster integration for the lock that displayed. 

Is the proper procedure within the HACS page, click on the keymaster card, then in the upper right corner of the 3 dots, expand the menu and select delete?

**Comment by firstof9** [comment]
> Is the proper procedure within the HACS page, click on the keymaster card, then in the upper right corner of the 3 dots, expand the menu and select delete?

No, removing the integration from the `Devices and Services` in the HA configuration screen first is the correct way, this should have removed the configuration from HA for you.
