### ISSUE TITLE
ISSUE: Error doing job: Future exception was never retrieved ('Lock jammed')

### ISSUE THREAD

**Issue by oblivioncth** [FutureTense/keymaster#333]
**Describe the bug**
Not sure when this started as I hadn't audited my logs in a while, but I'm getting this error periodically. As far as I can tell everything else is working as intended.

Somewhat similar to previously resolved issues.

**Environment (please complete the following information):**

- OS: HassOS
- Type of system: KVM Virtual Machine
- Home Assistant version: 2023.4.6
- Hassio
- Component version: v0.0.85
- Z-Wave integration name: zwave_js
- Lock make and model: Kwikset 916 Z-Wave

**Logs**
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/keymaster/helpers.py:300
Integration: keymaster (documentation, issues)
First occurred: 1:22:24 PM (8 occurrences)
Last logged: 10:16:02 PM

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/keymaster/helpers.py", line 300, in handle_state_change
    int(alarm_type_state.state)
ValueError: invalid literal for int() with base 10: 'Lock jammed'

```

**Screenshots**
N/A

**Additional context**
This made me realize that the `Access Control State` sensor for my lock does show "Lock Jammed" though I don't know why as it's been working fine... Seems like it may be a limitation of Z-wave JS clearing the state after a previous jam that was fixed recently but hasn't been pulled in by HA yet.

**Comment by raman325** [comment]
reconfigure your keymaster config entry and switch to `sensor.fake` for alarm level and alarm type. These are holdovers from the older zwave integrations, I don't believe they are needed for zwave_js

**Comment by oblivioncth** [comment]
If this hold to be true, I guess the instructions should be updated to indicate this then.

I've set the sensor to fake for both and will report back after a day or so to confirm that I don't see the error anymore and that nothing else has stopped working correctly.

Thanks.

**EDIT:** I knew there was almost no way it was a coincidence that the Z-Wave JS integration just happened to update. Thanks for bumping that too!

**Comment by oblivioncth** [comment]
Well everything seemed to be fine, so I just wanted to test to make sure I could still change the lock codes with the fake sensors in place and now I have a different problem.

When disabling and re-enabling the slot the PIN Status gets stuck on "Adding" and in the log book for my lock I see
`Lock] Front Door fired Notification CC 'notification' event 'Access Control': 'New user code not added due to duplicate code` no matter what code I enter (and they certainly aren't duplicates).

I can open another issue for this here but it seems like it might be more of a Z-Wave JS issue.

**Comment by firstof9** [comment]
The message is coming from your lock.

**Comment by oblivioncth** [comment]
> The message is coming from your lock.

Directly? As in HA is just blindly forwarding the message and it's nothing specific from Z-Wave JS or HA? Well then great, the lock's bugging out then :(

I'd appreciate confirmation I'm understanding this correctly so I can attempt to fix it otherwise as I'd like to confirm I can still manage lock codes correctly before marking this as resolved.

**Comment by firstof9** [comment]
The notifications come from the lock itself, zwavejs and HA just pass the info along, _sometimes_ this error will happen if the PIN isn't 4 or 6 digits in length. Nothing more, nothing less.

**Comment by oblivioncth** [comment]
Great.

Well, thank you for the clarification. I'll close this for now since the original issue has ceased and it might take me a while to figure out whats going on with my lock.

I can always reopen this later if I fix the lock and still have issues that seem related to faking the sensors.
