### ISSUE TITLE
ISSUE: Release notes say to call keymaster.generate but no service exists 

### ISSUE THREAD

**Issue by uSlackr** [FutureTense/keymaster#342]
**Describe the bug**
Release notes say to call keymaster.generate but no service exists 

**Environment (please complete the following information):**

- OS: HassOS 11.1
- Type of system that HA is running on: HA Blue
- Home Assistant version: 2023.11.2
- Hassio Core
- Component version:  0.0.86
- Z-Wave integration name: zwave_js UI
- Lock make and model: Yale YRD622

**Logs**
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/connection.py:268
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 7:24:16 PM (2 occurrences)
Last logged: 7:26:08 PM

[281472451522880] Error handling message: Unable to find service keymaster.generate (unknown_error) Greg from 192.168.1.125 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0)

**Screenshots**
NA

**Additional context**

**Comment by firstof9** [comment]
`keymaster.generate_package`

**Comment by raman325** [comment]
looks like @firstof9 already updated the release notes, so closing this, but comment if you have any additional questions
