### ISSUE TITLE
ISSUE: DEVICE_CLASS_CONNECTIVITY was used from keymaster, this is a deprecated constant

### ISSUE THREAD

**Issue by def1149** [FutureTense/keymaster#349]
**Describe the bug**
DEVICE_CLASS_CONNECTIVITY was used from keymaster, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.CONNECTIVITY instead, please create a bug report at https://github.com/FutureTense/keymaster/issues
**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: HA Yellow 
- Home Assistant version: 2024.1.0b0
- Hassio/Docker/Core? 11.3.rc1
- Component version: [e.g. 0.1.2]
- Z-Wave integration name: Z-Wave JS
- Lock make and model: Schlage BE469

**Logs**
DEVICE_CLASS_CONNECTIVITY was used from keymaster, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.CONNECTIVITY instead, please create a bug report at https://github.com/FutureTense/keymaster/issues
**Environment (please complete the following information):**
**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by rchorowitz** [comment]
We have not been able to use our locks in weeks due to this error. 

Does anyone have a solution?

![Screenshot 2024-01-24 215821](https://github.com/FutureTense/keymaster/assets/140976445/d1207470-de42-4baa-995a-55a8f8445d63)

**Comment by def1149** [comment]
I've seen this deprecation warning at boot time. It won't cause issues until 2025.1 if it's not fixed.
I don't think that is your problem 
core 2024.1.5
OS 11.4
My BE469ZP is working fine

**Comment by rchorowitz** [comment]
Happened after the last core update I believe.... Any suggestions on how to diagnose or repair?

Core: 2024.1.5
Supervisor: 2023.12.1
Operating System: 11.4
Frontend: 20240104.0

**Comment by def1149** [comment]
Looks like your Keymaster setup has a problem. All its entities are missing Check Settings>Devices & Services>Key Master and enable debugging and see if anything shows when you end debugging and download the log
I'd check your lock in Z-Wave and see if it's working. You should be able to lock and unlock it there and view a lot of sensor data
Try a hard reboot of HA. If that doesn't work you need to reinstall 
I'm not an expert with Key Master. I'd create a separate problem report

**Comment by jeprice77** [comment]
I updated Home Assistant core today to version 2024.1.6 and it broke my kwikset lock that uses keymaster.   I got the same results as others described here and the following warning in the system log.

DEVICE_CLASS_CONNECTIVITY was used from keymaster, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.CONNECTIVITY instead, please create a bug report at https://github.com/FutureTense/keymaster/issues

I restored my backup made before the update, and everything started working again.  I will wait to see what happens before updating Home Assistant again.

**Comment by firstof9** [comment]
This is a warning and non-blocking error message, it doesn't stop anything from working.

**Comment by jeprice77** [comment]
I knew it was a warning, but can't explain why the newer version of Home
Assistant Core makes it stop working.  I rolled back the version using my
backup and it works fine.  I am not sure why.  Keymaster works fine with
Home assistant version 2023.12.4 works but I can't get it to work with
2024.1.6.

**Comment by firstof9** [comment]
Runs fine here on 2024.1.5, you'd need to get the _actual_ error from `home-assistant.log` for any kind of troubleshooting.

**Comment by rchorowitz** [comment]
I removed Keymaster and reinstalled.  I can control the lock, but the auto lock feature no longer works.  It counts down but does not throw the bolt.

**Comment by firstof9** [comment]
> I removed Keymaster and reinstalled. I can control the lock, but the auto lock feature no longer works. It counts down but does not throw the bolt.

Unrelated to this issue, please open a new issue.

**Comment by bharvey88** [comment]
confirmed log warnings gone after updating to 0.0.88
