### ISSUE TITLE
ISSUE: Unable to select user code sensor for Schlage Connect Z-Wave Lock

### ISSUE THREAD

**Issue by thefinn93** [FutureTense/keymaster#350]
**Describe the bug**
Per [the Install wiki page](https://github.com/FutureTense/keymaster/wiki/Install-the-integration#7--user-code-sensor) I should be able to select a user code sensor to determine which user code was used to unlock the door, however I'm not seeing an option to select that sensor, only `sensor.fake`

My lock is the Schlage BE469ZP mentioned on the wiki page under that section.

**Environment (please complete the following information):**

- OS: [e.g. HassOS/Raspbian/CentOS]: HassOS
- Type of system that HA is running on: [e.g. RPi3/NUC/Synology]: Rpi
- Home Assistant version: [e.g. 0.105.5] 2024.1.2
- Hassio/Docker/Core? Hassio
- Component version: [e.g. 0.1.2] 0.0.87
- Z-Wave integration name: [e.g. zwave_js] zwave_js
- Lock make and model: [e.g. Schlage BE469] Schlage BE469ZP

**Logs**
Not seeing any relevant log entries

**Screenshots**
![image](https://github.com/FutureTense/keymaster/assets/692970/777641a3-2d6a-489c-8409-48d8849af2ce)

**Additional context**
I just installed this lock and added it to HA an hour or two ago, and added HACS and this component. I'm not sure if there's some delay in this sensor showing up or something?

**Comment by firstof9** [comment]
1) you likely won't want to utilize 30 slots, you should lower that number to the amount of codes you're actually going to use
2) you will not see the extra sensors unless they are enabled, they are not required anyways

**Comment by thefinn93** [comment]
Thanks! How do I enable the extra sensors?

**Comment by firstof9** [comment]
enable them from ZwaveJS they'd be a disabled entity under the "sensors" category.

**Comment by thefinn93** [comment]
under Settings -> Add Ons -> Z-Wave JS -> Configuration? I'm not seeing anything about sensors, even with "Show unused optional configuration options" enabled

**Comment by firstof9** [comment]
no the zwavejs integration in HA

**Comment by firstof9** [comment]
keep in mind you do not _need_ these sensors, there are events emitted that will output the name you've associated with a code slot

**Comment by thefinn93** [comment]
how do I see those events then? I tried entering a user code and I wasn't able to find the relevant event. Also not seeing any option in the Z-Wave JS integration to enable any extra sensors. I looked in the hub configuration and the device specific configuration. Unless it's called something weird?

**Comment by firstof9** [comment]
It's explained in [the wiki here](https://github.com/FutureTense/keymaster/wiki/(Advanced)-Create-your-own-automations-based-on-lock-state-changes).

**Comment by thefinn93** [comment]
ahh, so the data won't just show up in the stock log book because it's like an extra attribute to the event. Thanks.
