### ISSUE TITLE
ISSUE:  Code slot PIN statuses stuck at "deleting" or "adding"

### ISSUE THREAD

**Issue by KevinDosi** [FutureTense/keymaster#351]
**Describe the bug**
When I attempt to add or remove a PIN code, the PIN status stays at "deleting" or "adding" forever. 

**Environment (please complete the following information):**

- OS: HASSOS
- Type of system that HA is running on: NUC
- Home Assistant version: 2024.1
- Hassio/Docker/Core? Core
- Component version: [e.g. 0.1.2]
- Z-Wave integration name: zwave_js

**Screenshots**
<img width="1162" alt="Screenshot 2024-01-14 at 12 09 27 AM" src="https://github.com/FutureTense/keymaster/assets/64453695/b015c327-3487-49ef-b511-8100e0ff4d07">

**Comment by firstof9** [comment]
duplicate: #270
