### ISSUE TITLE
Question on use of Friendly Names for locks and also on auto clock parameters?

### ISSUE THREAD

**Issue by Roachforlife** [FutureTense/keymaster#358]
Sorry not really a bug or feature request but just some general questions
1. I set up several locks such as 'front_door' and 'garage_door'. When getting notifications they dont look the nicest. Any way to set up some sort of 'Friendly Name' so it would instead say 'Front Door'?

2. I saw there is auto close feature and I can set the time outs, great stuff. I didnt see anywhere in documentation two things
    a. What are the default values for the daytime and night time ones? (ie what time of the day does it switch)
   b. Is there a way to modify this?

Thanks again!

Environment (please complete the following information):

    OS: Windows for me, HA for keymaster
    Type of system that HA is running on: QNAP VM
    Home Assistant version: 2024.3.2
    Hassio/Docker/Core? VM
    Component version: 0.0.88
    Z-Wave integration name: zwave_js
    Lock make and model: Schlage BE469ZP (zwave plus)

**Comment by firstof9** [comment]
> 1. Any way to set up some sort of 'Friendly Name' so it would instead say 'Front Door'?

Notification script is 100% your doing, modify the example as you see fit.

As for 2, I don't use the autolock feature myself, but there's a ongoing thread that covers many of the features:
https://community.home-assistant.io/t/keymaster-z-wave-lock-manager-and-scheduler/166419/1932

**Comment by Roachforlife** [comment]
Thank you, I posted over there as well!
