### ISSUE TITLE
ISSUE: handle_state_change error

### ISSUE THREAD

**Issue by jprokopowich** [FutureTense/keymaster#366]
**Describe the bug**
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/keymaster/helpers.py:271
integration: keymaster (documentation, issues)
First occurred: 3:04:15 PM (2 occurrences)
Last logged: 3:24:37 PM

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/keymaster/helpers.py", line 271, in handle_state_change
    new_state = event.data["new_state"]
                ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'

**Environment (please complete the following information):**

- OS: HassOS
- Type of system that HA is running on: rasp4
- Home Assistant version: 2024.5.3
- Hassio/Docker/Core? Hsssio
- Component version: v0.0.91
- Z-Wave integration name:  zwave_js]
- Lock make and model: Weiser and kwikset

**Logs**

**Screenshots**

**Additional context**

**Comment by firstof9** [comment]
Update to `v0.0.92` and see if your error persists.

**Comment by jprokopowich** [comment]
upgraded to v0.0.92 and restarted HA yesterday and saw this this morning,

Logger: homeassistant.helpers.event
Source: helpers/event.py:327
First occurred: 7:07:40 AM (3 occurrences)
Last logged: 8:23:15 AM
Error while dispatching event for lock.mudroom to <Job track state_changed event ['lock.mudroom'] HassJobType.Callback functools.partial(<function handle_state_change at 0x7f2b1c37e0>, <HomeAssistant RUNNING>, <ConfigEntry entry_id=e1e613bd83ca10b560b5544e74d84f99 version=2 domain=keymaster title=mudroom state=ConfigEntryState.LOADED unique_id=mudroom>)>

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 327, in _async_dispatch_entity_id_event
    hass.async_run_hass_job(job, event)
  File "/usr/src/homeassistant/homeassistant/core.py", line 947, in async_run_hass_job
    hassjob.target(*args)
  File "/config/custom_components/keymaster/helpers.py", line 272, in handle_state_change
    new_state = event.data["new_state"]
                ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'data'
