### ISSUE TITLE
ISSUE:  Lost Notifications after Core update 2024.5.5

### ISSUE THREAD

**Issue by beyondunreal79** [FutureTense/keymaster#371]
After yesterday's core update (core_2024.5.5) I no longer get notifications when my door lock codes are entered.  Also lost an auto alarmo disarm automation based on an event.  I noticed that listening to events under keymaster_lock_state_changed
no longer show any events up entering coed into my lock
![image](https://github.com/FutureTense/keymaster/assets/45919008/7a883bfa-3278-4693-82e1-80b26f19bc2c)

As another person posted, I also have the pin status stuck on adding, and one of them stuck on deleting.
![image](https://github.com/FutureTense/keymaster/assets/45919008/8476e5c1-bb28-442b-8266-2ae9b0657d57)

I am running HAOS 
zwave-js-ui: 9.13.3
zwave-js: 12.9.1
Core 2024.6.1
Supervisor 2024.06.0
Operating System 12.3
Frontend 20240605.0
Lock type. Yale assure

**Comment by firstof9** [comment]
Dupe #369
