### ISSUE TITLE
ISSUE: [custom_components.keymaster.binary_sensor] Can't access Z-Wave JS client.

### ISSUE THREAD

**Issue by vavallee** [FutureTense/keymaster#379]
**Describe the bug**

I just setup keymaster for the first time with my ZWAVE Yale Assure Lock 2 SL.
When I try to change or add a pin, the status is stuck at adding or deleting.
In the logs I see.
[custom_components.keymaster.binary_sensor] Can't access Z-Wave JS client.

**Environment (please complete the following information):**

- OS: Ubuntu / Container
- Type of system that HA is running on: Kubernetes
- Home Assistant version: 2024.5.4
- Hassio/Docker/Core? Core
- Component version: 0.0.98
- Z-Wave integration name:  zwave JS UI
- Lock make and model: Yale Assure Lock 2 SL Touchscreen

**Logs**
 2024-07-11 22:46:39.762 ERROR (MainThread) [custom_components.keymaster.binary_sensor] Can't access Z-Wave JS client.                              │
│ Traceback (most recent call last):                                                                                                                 │
│   File "/config/custom_components/keymaster/binary_sensor.py", line 130, in async_update                                                           │
│     client = zwave_entry.runtime_data[ZWAVE_JS_DATA_CLIENT]                                                                                        │
│              ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                              │
│ AttributeError: 'ConfigEntry' object has no attribute 'runtime_data'

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Try updating your home assistant.

**Comment by vavallee** [comment]
That worked, all good now thanks!
