### ISSUE TITLE
Code rewrite and update

### ISSUE THREAD

**Issue by ccsliinc** [FutureTense/keymaster#38]
Hello all, I would like to talk to one of the project maintainers.  I have some updated code I would like to share and discuss if wanted.  Its based upon this work, but i would like to show and discuss.

**Comment by smiller171** [comment]
Typically wouldn't you just open a PR if you've already written the code?

**Comment by ccsliinc** [comment]
Typically I would, but I rewrote the whole thing from the ground using the lockmanager as a guide.  I didnt want to pr it, unless I actually had a conversation with someone as it may be quite difficult to read, and I am 99% done with the backend, but need to work on the frontend.  I didnt know if anyone was interested in a helping hand.  If you would like me to make a brach and pr it not a problem.  Thoughts?

**Comment by smiller171** [comment]
Oh I'm not a maintainer of this project, was just looking through the issues to try to find out why he moved to this repo from the old `lock-manager` repo if I could and saw this.

**Comment by raman325** [comment]
@ccsliinc hit me up on discord and I'll add you: raman325#4076

**Comment by raman325** [comment]
> Oh I'm not a maintainer of this project, was just looking through the issues to try to find out why he moved to this repo from the old `lock-manager` repo if I could and saw this.

the latest version of HA does not support `lock-manager` because of the dash in the name. The project was renamed so it could continue to work. Functionally they achieve the same thing although there have been a lot of changes in the migration to make things more efficient

**Comment by smiller171** [comment]
Thanks for that info @raman325! IMO it probably makes sense to put that in the readme of both repos
