### ISSUE TITLE
ISSUE: Adding additional locks but no Status in the Overview Lock Dashboard

### ISSUE THREAD

**Issue by Sammy-cmd** [FutureTense/keymaster#382]
**Describe the bug**

I am unable to view the locked status of any of the child locks added to Keymaster in the overview dashboard. The necessary entities do not seem to exist in ymal in order to add them to the dashboard.

**Environment (please complete the following information):**

- OS: [e.g. HassOS13.1 / HACore 2024.8.3]
- Type of system that HA is running on: NUC / Oracle VM VirtualBox 
- Home Assistant version: [e.g. 0.105.5]
- Hassio/Docker/Core? No
- Component version: 0.98 ?
- Z-Wave integration name: zwave_js
- Lock make and model: Kwikset Home Connect 620

**Logs**
```
2024-09-01 08:18:06.059 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration keymaster which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-01 08:18:06.062 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-01 08:18:06.064 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration blueiris which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-09-01 08:18:20.350 WARNING (MainThread) [homeassistant.components.heos] 10.0.0.33 is not logged in to a HEOS account and will be unable to retrieve HEOS favorites: Use the 'heos.sign_in' service to sign-in to a HEOS account
2024-09-01 08:18:21.535 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'blueiris' calls async_forward_entry_setup for integration, blueiris with title: Coventry and entry_id: XXXXXXXXXXXXXXXXX, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/blueiris/managers/home_assistant.py, line 121: await load(self._config_manager.config_entry, domain), please create a bug report at https://github.com/elad-bar/ha-blueiris/issues
2024-09-01 08:18:23.892 WARNING (MainThread) [slixmpp.stringprep] Using slower stringprep, consider compiling the faster cython/libidn one.
2024-09-01 08:18:24.503 ERROR (MainThread) [homeassistant.components.device_tracker] Platform mobile_app does not generate unique IDs. ID XXXXXXXXXXXXXXXXXXXXX already exists - ignoring device_tracker.teds_13_pro
2024-09-01 08:18:25.123 WARNING (MainThread) [homeassistant.config_entries] Config entry 'Backyard TV' for androidtv_remote integration could not authenticate: Need to pair again
2024-09-01 08:18:30.397 ERROR (MainThread) [custom_components.keymaster.binary_sensor] Z-Wave integration not found
2024-09-01 08:18:30.397 WARNING (MainThread) [homeassistant.components.binary_sensor] Platform keymaster not ready yet: None; Retrying in background in 30 seconds
```
... truncated a bunch of issues with blueiris not of concern here ...

**Screenshots**
As seen here for the first and parent lock, the entity: lock.front_door_lock shows the status.
![image](https://github.com/user-attachments/assets/cc969670-950d-476a-a819-faafea35958a)

Not only does it not show in the child locks, the entity doesn't seem to even exist. In other words, I cannot find an entity called lock.laundry_room_door_lock or lock.master_bedroom_lock
![image](https://github.com/user-attachments/assets/fb1f4737-6193-4047-9e64-de0eae5fda5f)

![image](https://github.com/user-attachments/assets/0f776ead-ffbf-4541-9402-6d2a93b417fa)

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by firstof9** [comment]
Make sure the files have generated in your `packages` directory.

**Comment by Sammy-cmd** [comment]
The Package is there:

![image](https://github.com/user-attachments/assets/9085ba98-0b5f-48f6-88f3-bd28097b779d)

![image](https://github.com/user-attachments/assets/372ae070-7a25-42c2-8078-c41cda73ca8a)

Which I copy/pasted to here:

![image](https://github.com/user-attachments/assets/09a16e1d-9247-4fd9-801c-03f53d816bc2)

![image](https://github.com/user-attachments/assets/3b22cf49-cf68-4ce9-959a-219c27dca792)

`title: master_bedroom_door Codes and Configuration
path: keypad-master_bedroom_door
icon: mdi:lock-smart
panel: false
badges:
  - input_text.master_bedroom_door_lockname
  - input_text.master_bedroom_door_front_door_parent
  - input_boolean.master_bedroom_door_lock_notifications
  - input_boolean.master_bedroom_door_dooraccess_notifications
  - input_boolean.master_bedroom_door_garageacess_notifications
  - type: entity
    entity: lock.boltchecked_master_bedroom_door_lock
  - entity: binary_sensor.fake
  - entity: input_text.keymaster_master_bedroom_door_autolock_door_time_day
  - entity: input_text.keymaster_master_bedroom_door_autolock_door_time_night
  - entity: input_boolean.keymaster_master_bedroom_door_autolock
  - entity: timer.keymaster_master_bedroom_door_autolock
cards:
  - type: vertical-stack
    cards:
      - content: |
          ## Code 1
        type: markdown
      - type: entities
        show_header_toggle: false
        entities:
          - entity: input_text.master_bedroom_door_name_1
          - entity: input_text.master_bedroom_door_pin_1
          - entity: input_boolean.enabled_master_bedroom_door_1
          - entity: input_boolean.notify_master_bedroom_door_1
          - type: divider
          - entity: input_boolean.override_parent_master_bedroom_door_1
          - type: divider
          - entity: sensor.connected_master_bedroom_door_1
            state_color: true
          - entity: binary_sensor.active_master_bedroom_door_1
            state_color: true
          - type: custom:fold-entity-row
            head:
              type: section
              label: Advanced Options
            entities:
              - entity: input_boolean.reset_codeslot_master_bedroom_door_1
              - type: divider
              - entity: input_boolean.accesslimit_master_bedroom_door_1
              - entity: input_number.accesscount_master_bedroom_door_1
                type: custom:numberbox-card
                icon: mdi:key-variant
                speed: 250
              - type: divider
              - entity: input_boolean.daterange_master_bedroom_door_1
              - entity: input_datetime.start_date_master_bedroom_door_1
              - entity: input_datetime.end_date_master_bedroom_door_1
              - type: custom:fold-entity-row
                head:
                  type: section
                  label: Custom Weekdays
                entities:
                  - input_boolean.sun_master_bedroom_door_1
                  - input_boolean.sun_inc_master_bedroom_door_1
                  - input_datetime.sun_start_date_master_bedroom_door_1
                  - input_datetime.sun_end_date_master_bedroom_door_1
                  - type: divider
                  - input_boolean.mon_master_bedroom_door_1
                  - input_boolean.mon_inc_master_bedroom_door_1
                  - input_datetime.mon_start_date_master_bedroom_door_1
                  - input_datetime.mon_end_date_master_bedroom_door_1
                  - type: divider
                  - input_boolean.tue_master_bedroom_door_1
                  - input_boolean.tue_inc_master_bedroom_door_1
                  - input_datetime.tue_start_date_master_bedroom_door_1
                  - input_datetime.tue_end_date_master_bedroom_door_1
                  - type: divider
                  - input_boolean.wed_master_bedroom_door_1
                  - input_boolean.wed_inc_master_bedroom_door_1
                  - input_datetime.wed_start_date_master_bedroom_door_1
                  - input_datetime.wed_end_date_master_bedroom_door_1
                  - type: divider
                  - input_boolean.thu_master_bedroom_door_1
                  - input_boolean.thu_inc_master_bedroom_door_1
                  - input_datetime.thu_start_date_master_bedroom_door_1
                  - input_datetime.thu_end_date_master_bedroom_door_1
                  - type: divider
                  - input_boolean.fri_master_bedroom_door_1
                  - input_boolean.fri_inc_master_bedroom_door_1
                  - input_datetime.fri_start_date_master_bedroom_door_1
                  - input_datetime.fri_end_date_master_bedroom_door_1
                  - type: divider
                  - input_boolean.sat_master_bedroom_door_1
                  - input_boolean.sat_inc_master_bedroom_door_1
                  - input_datetime.sat_start_date_master_bedroom_door_1
                  - input_datetime.sat_end_date_master_bedroom_door_1
  - type: vertical-stack
    cards:
      - content: |
          ## Code 2
        type: markdown
      - type: entities
        show_header_toggle: false
        entities:
          - entity: input_text.master_bedroom_door_name_2
          - entity: input_text.master_bedroom_door_pin_2
          - entity: input_boolean.enabled_master_bedroom_door_2
          - entity: input_boolean.notify_master_bedroom_door_2
          - type: divider
          - entity: input_boolean.override_parent_master_bedroom_door_2
          - type: divider
          - entity: sensor.connected_master_bedroom_door_2
            state_color: true
          - entity: binary_sensor.active_master_bedroom_door_2
            state_color: true
          - type: custom:fold-entity-row
            head:
              type: section
              label: Advanced Options
            entities:
              - entity: input_boolean.reset_codeslot_master_bedroom_door_2
              - type: divider
              - entity: input_boolean.accesslimit_master_bedroom_door_2
              - entity: input_number.accesscount_master_bedroom_door_2
                type: custom:numberbox-card
                icon: mdi:key-variant
                speed: 250
              - type: divider
              - entity: input_boolean.daterange_master_bedroom_door_2
              - entity: input_datetime.start_date_master_bedroom_door_2
              - entity: input_datetime.end_date_master_bedroom_door_2
              - type: custom:fold-entity-row
                head:
                  type: section
                  label: Custom Weekdays
                entities:
                  - input_boolean.sun_master_bedroom_door_2
                  - input_boolean.sun_inc_master_bedroom_door_2
                  - input_datetime.sun_start_date_master_bedroom_door_2
                  - input_datetime.sun_end_date_master_bedroom_door_2
                  - type: divider
                  - input_boolean.mon_master_bedroom_door_2
                  - input_boolean.mon_inc_master_bedroom_door_2
                  - input_datetime.mon_start_date_master_bedroom_door_2
                  - input_datetime.mon_end_date_master_bedroom_door_2
                  - type: divider
                  - input_boolean.tue_master_bedroom_door_2
                  - input_boolean.tue_inc_master_bedroom_door_2
                  - input_datetime.tue_start_date_master_bedroom_door_2
                  - input_datetime.tue_end_date_master_bedroom_door_2
                  - type: divider
                  - input_boolean.wed_master_bedroom_door_2
                  - input_boolean.wed_inc_master_bedroom_door_2
                  - input_datetime.wed_start_date_master_bedroom_door_2
                  - input_datetime.wed_end_date_master_bedroom_door_2
                  - type: divider
                  - input_boolean.thu_master_bedroom_door_2
                  - input_boolean.thu_inc_master_bedroom_door_2
                  - input_datetime.thu_start_date_master_bedroom_door_2
                  - input_datetime.thu_end_date_master_bedroom_door_2
                  - type: divider
                  - input_boolean.fri_master_bedroom_door_2
                  - input_boolean.fri_inc_master_bedroom_door_2
                  - input_datetime.fri_start_date_master_bedroom_door_2
                  - input_datetime.fri_end_date_master_bedroom_door_2
                  - type: divider
                  - input_boolean.sat_master_bedroom_door_2
                  - input_boolean.sat_inc_master_bedroom_door_2
                  - input_datetime.sat_start_date_master_bedroom_door_2
                  - input_datetime.sat_end_date_master_bedroom_door_2
  - type: vertical-stack
    cards:
      - content: |
          ## Code 3
        type: markdown
      - type: entities
        show_header_toggle: false
        entities:
          - entity: input_text.master_bedroom_door_name_3
          - entity: input_text.master_bedroom_door_pin_3
          - entity: input_boolean.enabled_master_bedroom_door_3
          - entity: input_boolean.notify_master_bedroom_door_3
          - type: divider
          - entity: input_boolean.override_parent_master_bedroom_door_3
          - type: divider
          - entity: sensor.connected_master_bedroom_door_3
            state_color: true
          - entity: binary_sensor.active_master_bedroom_door_3
            state_color: true
          - type: custom:fold-entity-row
            head:
              type: section
              label: Advanced Options
            entities:
              - entity: input_boolean.reset_codeslot_master_bedroom_door_3
              - type: divider
              - entity: input_boolean.accesslimit_master_bedroom_door_3
              - entity: input_number.accesscount_master_bedroom_door_3
                type: custom:numberbox-card
                icon: mdi:key-variant
                speed: 250
              - type: divider
              - entity: input_boolean.daterange_master_bedroom_door_3
              - entity: input_datetime.start_date_master_bedroom_door_3
              - entity: input_datetime.end_date_master_bedroom_door_3
              - type: custom:fold-entity-row
                head:
                  type: section
                  label: Custom Weekdays
                entities:
                  - input_boolean.sun_master_bedroom_door_3
                  - input_boolean.sun_inc_master_bedroom_door_3
                  - input_datetime.sun_start_date_master_bedroom_door_3
                  - input_datetime.sun_end_date_master_bedroom_door_3
                  - type: divider
                  - input_boolean.mon_master_bedroom_door_3
                  - input_boolean.mon_inc_master_bedroom_door_3
                  - input_datetime.mon_start_date_master_bedroom_door_3
                  - input_datetime.mon_end_date_master_bedroom_door_3
                  - type: divider
                  - input_boolean.tue_master_bedroom_door_3
                  - input_boolean.tue_inc_master_bedroom_door_3
                  - input_datetime.tue_start_date_master_bedroom_door_3
                  - input_datetime.tue_end_date_master_bedroom_door_3
                  - type: divider
                  - input_boolean.wed_master_bedroom_door_3
                  - input_boolean.wed_inc_master_bedroom_door_3
                  - input_datetime.wed_start_date_master_bedroom_door_3
                  - input_datetime.wed_end_date_master_bedroom_door_3
                  - type: divider
                  - input_boolean.thu_master_bedroom_door_3
                  - input_boolean.thu_inc_master_bedroom_door_3
                  - input_datetime.thu_start_date_master_bedroom_door_3
                  - input_datetime.thu_end_date_master_bedroom_door_3
                  - type: divider
                  - input_boolean.fri_master_bedroom_door_3
                  - input_boolean.fri_inc_master_bedroom_door_3
                  - input_datetime.fri_start_date_master_bedroom_door_3
                  - input_datetime.fri_end_date_master_bedroom_door_3
                  - type: divider
                  - input_boolean.sat_master_bedroom_door_3
                  - input_boolean.sat_inc_master_bedroom_door_3
                  - input_datetime.sat_start_date_master_bedroom_door_3
                  - input_datetime.sat_end_date_master_bedroom_door_3
  - type: vertical-stack
    cards:
      - content: |
          ## Code 4
        type: markdown
      - type: entities
        show_header_toggle: false
        entities:
          - entity: input_text.master_bedroom_door_name_4
          - entity: input_text.master_bedroom_door_pin_4
          - entity: input_boolean.enabled_master_bedroom_door_4
          - entity: input_boolean.notify_master_bedroom_door_4
          - type: divider
          - entity: input_boolean.override_parent_master_bedroom_door_4
          - type: divider
          - entity: sensor.connected_master_bedroom_door_4
            state_color: true
          - entity: binary_sensor.active_master_bedroom_door_4
            state_color: true
          - type: custom:fold-entity-row
            head:
              type: section
              label: Advanced Options
            entities:
              - entity: input_boolean.reset_codeslot_master_bedroom_door_4
              - type: divider
              - entity: input_boolean.accesslimit_master_bedroom_door_4
              - entity: input_number.accesscount_master_bedroom_door_4
                type: custom:numberbox-card
                icon: mdi:key-variant
                speed: 250
              - type: divider
              - entity: input_boolean.daterange_master_bedroom_door_4
              - entity: input_datetime.start_date_master_bedroom_door_4
              - entity: input_datetime.end_date_master_bedroom_door_4
              - type: custom:fold-entity-row
                head:
                  type: section
                  label: Custom Weekdays
                entities:
                  - input_boolean.sun_master_bedroom_door_4
                  - input_boolean.sun_inc_master_bedroom_door_4
                  - input_datetime.sun_start_date_master_bedroom_door_4
                  - input_datetime.sun_end_date_master_bedroom_door_4
                  - type: divider
                  - input_boolean.mon_master_bedroom_door_4
                  - input_boolean.mon_inc_master_bedroom_door_4
                  - input_datetime.mon_start_date_master_bedroom_door_4
                  - input_datetime.mon_end_date_master_bedroom_door_4
                  - type: divider
                  - input_boolean.tue_master_bedroom_door_4
                  - input_boolean.tue_inc_master_bedroom_door_4
                  - input_datetime.tue_start_date_master_bedroom_door_4
                  - input_datetime.tue_end_date_master_bedroom_door_4
                  - type: divider
                  - input_boolean.wed_master_bedroom_door_4
                  - input_boolean.wed_inc_master_bedroom_door_4
                  - input_datetime.wed_start_date_master_bedroom_door_4
                  - input_datetime.wed_end_date_master_bedroom_door_4
                  - type: divider
                  - input_boolean.thu_master_bedroom_door_4
                  - input_boolean.thu_inc_master_bedroom_door_4
                  - input_datetime.thu_start_date_master_bedroom_door_4
                  - input_datetime.thu_end_date_master_bedroom_door_4
                  - type: divider
                  - input_boolean.fri_master_bedroom_door_4
                  - input_boolean.fri_inc_master_bedroom_door_4
                  - input_datetime.fri_start_date_master_bedroom_door_4
                  - input_datetime.fri_end_date_master_bedroom_door_4
                  - type: divider
                  - input_boolean.sat_master_bedroom_door_4
                  - input_boolean.sat_inc_master_bedroom_door_4
                  - input_datetime.sat_start_date_master_bedroom_door_4
                  - input_datetime.sat_end_date_master_bedroom_door_4
  - type: vertical-stack
    cards:
      - content: |
          ## Code 5
        type: markdown
      - type: entities
        show_header_toggle: false
        entities:
          - entity: input_text.master_bedroom_door_name_5
          - entity: input_text.master_bedroom_door_pin_5
          - entity: input_boolean.enabled_master_bedroom_door_5
          - entity: input_boolean.notify_master_bedroom_door_5
          - type: divider
          - entity: input_boolean.override_parent_master_bedroom_door_5
          - type: divider
          - entity: sensor.connected_master_bedroom_door_5
            state_color: true
          - entity: binary_sensor.active_master_bedroom_door_5
            state_color: true
          - type: custom:fold-entity-row
            head:
              type: section
              label: Advanced Options
            entities:
              - entity: input_boolean.reset_codeslot_master_bedroom_door_5
              - type: divider
              - entity: input_boolean.accesslimit_master_bedroom_door_5
              - entity: input_number.accesscount_master_bedroom_door_5
                type: custom:numberbox-card
                icon: mdi:key-variant
                speed: 250
              - type: divider
              - entity: input_boolean.daterange_master_bedroom_door_5
              - entity: input_datetime.start_date_master_bedroom_door_5
              - entity: input_datetime.end_date_master_bedroom_door_5
              - type: custom:fold-entity-row
                head:
                  type: section
                  label: Custom Weekdays
                entities:
                  - input_boolean.sun_master_bedroom_door_5
                  - input_boolean.sun_inc_master_bedroom_door_5
                  - input_datetime.sun_start_date_master_bedroom_door_5
                  - input_datetime.sun_end_date_master_bedroom_door_5
                  - type: divider
                  - input_boolean.mon_master_bedroom_door_5
                  - input_boolean.mon_inc_master_bedroom_door_5
                  - input_datetime.mon_start_date_master_bedroom_door_5
                  - input_datetime.mon_end_date_master_bedroom_door_5
                  - type: divider
                  - input_boolean.tue_master_bedroom_door_5
                  - input_boolean.tue_inc_master_bedroom_door_5
                  - input_datetime.tue_start_date_master_bedroom_door_5
                  - input_datetime.tue_end_date_master_bedroom_door_5
                  - type: divider
                  - input_boolean.wed_master_bedroom_door_5
                  - input_boolean.wed_inc_master_bedroom_door_5
                  - input_datetime.wed_start_date_master_bedroom_door_5
                  - input_datetime.wed_end_date_master_bedroom_door_5
                  - type: divider
                  - input_boolean.thu_master_bedroom_door_5
                  - input_boolean.thu_inc_master_bedroom_door_5
                  - input_datetime.thu_start_date_master_bedroom_door_5
                  - input_datetime.thu_end_date_master_bedroom_door_5
                  - type: divider
                  - input_boolean.fri_master_bedroom_door_5
                  - input_boolean.fri_inc_master_bedroom_door_5
                  - input_datetime.fri_start_date_master_bedroom_door_5
                  - input_datetime.fri_end_date_master_bedroom_door_5
                  - type: divider
                  - input_boolean.sat_master_bedroom_door_5
                  - input_boolean.sat_inc_master_bedroom_door_5
                  - input_datetime.sat_start_date_master_bedroom_door_5
                  - input_datetime.sat_end_date_master_bedroom_door_5
`

**Comment by Sammy-cmd** [comment]
Repairs in Notifications:

![image](https://github.com/user-attachments/assets/c8c620bb-61ca-4a3f-a47b-4268a9fad32c)

Example of what one of them says:

![image](https://github.com/user-attachments/assets/ab9ac848-13b7-4bd1-8c49-98446840b993)

But I think that is because I haven't completed the setup of Pushover but am not sure.

**Comment by Sammy-cmd** [comment]
Well, the Master Bedroom Door Lock seems to be set up correctly but somehow I borked the Laundry Room Door Lock. I may exclude it and start over but does the configuration.ymal need to be manually edited to completely remove it?

**Comment by firstof9** [comment]
nothing needs to be edited to remove it

**Comment by Sammy-cmd** [comment]
I added another kwikset and I can't get the damn thing to set the handing and it won't stay connected to the network. It is closer than the front door but maybe there's interference. I put in a plug in Zooz zen07 up high centrally located and told Z-Wave js to reconfigure the network. Still no connection to two locks. I suppose I need more nodes but am using a Zooz 800 series lr usb stick?

**Comment by firstof9** [comment]
If all you have are the locks, then you don't actually have a mesh for routing. More powered nodes the better.

**Comment by Sammy-cmd** [comment]
> If all you have are the locks, then you don't actually have a mesh for routing. More powered nodes the better.

True dat!

I'll get more installed. I know this is an issue for sure, especially for the Laundry Room Lock because there's a 2 foot thick solid masonry fireplace along the entire wall between the family room and the laundry room and nothing is getting through that so I have to route around it.

I have a new issue. I removed the lock called Guest Bathroom Door from Z-Wave JS but it showed back up as "Node 6" with no information. I'm not sure how to properly exclude it and include it again. It should connect though because the Hub is in a room across the hall and it is closer than the Front Door Lock. There is, however, a tile shower in between. I'll put a powered node in between today and see what that does.

**Comment by Sammy-cmd** [comment]
Not sure what I've done now but need to restore from a saved backup.. How to do that? Or is there another thing I should do?

![image](https://github.com/user-attachments/assets/455c0763-9224-41cf-a1a4-418ece69973d)

**Comment by firstof9** [comment]
Your addon isn't running.

**Comment by Sammy-cmd** [comment]
Talk to me like I'm stupid! 😂

I'm brand noob to HA from Vera.

How do I make it run?

**Comment by firstof9** [comment]
I don't know, I don't use HAOS, you'll need to ask on their Discord.

**Comment by Sammy-cmd** [comment]
I will do that. Thank you for your help so far!

**Comment by Sammy-cmd** [comment]
> I don't know, I don't use HAOS, you'll need to ask on their Discord.

I got it cleared out. Adding ZUI over J-Wave JS is a process and I didn't read the instructions. In case anybody else comes across this issue, the solution is here:

https://community.home-assistant.io/t/cannot-connect-to-host-core-zwave-js-3000-ssl-default/376164/31?u=sammy2

**Comment by Sammy-cmd** [comment]
Now that that's fixed back to the original programming..

One of my Z-Wave Locks is non responsive.  I suspect it is due to its location in the Laundry Room which is behind a massive masonry fireplace which is the width of the family room and full height of the wall too. I think this log tells the story but am not sure.

```
2024-09-03T18:04:42.550Z DRIVER   all queues idle
2024-09-03T18:05:12.495Z DRIVER   all queues busy
2024-09-03T18:05:12.503Z SERIAL » 0x0103003bc7                                                         (5 bytes)
2024-09-03T18:05:12.509Z DRIVER » [REQ] [GetBackgroundRSSI]
2024-09-03T18:05:12.528Z SERIAL « [ACK]                                                                   (0x06)
2024-09-03T18:05:12.539Z SERIAL « 0x0107013ba3a1a1a6c7                                                 (9 bytes)
2024-09-03T18:05:12.543Z SERIAL » [ACK]                                                                   (0x06)
2024-09-03T18:05:12.560Z DRIVER « [RES] [GetBackgroundRSSI]
                                    channel 0: -93 dBm
                                    channel 1: -95 dBm
                                    channel 2: -95 dBm
                                    channel 3: -90 dBm
2024-09-03T18:05:12.571Z DRIVER   all queues idle
2024-09-03T18:05:42.500Z DRIVER   all queues busy
2024-09-03T18:05:42.508Z SERIAL » 0x0103003bc7                                                         (5 bytes)
2024-09-03T18:05:42.510Z DRIVER » [REQ] [GetBackgroundRSSI]
2024-09-03T18:05:42.534Z SERIAL « [ACK]                                                                   (0x06)
2024-09-03T18:05:42.540Z SERIAL « 0x0107013ba4a3a3a9cf                                                 (9 bytes)
2024-09-03T18:05:42.543Z SERIAL » [ACK]                                                                   (0x06)
2024-09-03T18:05:42.545Z DRIVER « [RES] [GetBackgroundRSSI]
                                    channel 0: -92 dBm
                                    channel 1: -93 dBm
                                    channel 2: -93 dBm
                                    channel 3: -87 dBm
2024-09-03T18:05:42.551Z DRIVER   all queues idle
2024-09-03T18:06:12.500Z DRIVER   all queues busy
2024-09-03T18:06:12.507Z SERIAL » 0x0103003bc7                                                         (5 bytes)
2024-09-03T18:06:12.510Z DRIVER » [REQ] [GetBackgroundRSSI]
2024-09-03T18:06:12.527Z SERIAL « [ACK]                                                                   (0x06)
2024-09-03T18:06:12.533Z SERIAL « 0x0107013ba3a1a1a6c7                                                 (9 bytes)
2024-09-03T18:06:12.538Z SERIAL » [ACK]                                                                   (0x06)
2024-09-03T18:06:12.542Z DRIVER « [RES] [GetBackgroundRSSI]
                                    channel 0: -93 dBm
                                    channel 1: -95 dBm
                                    channel 2: -95 dBm
                                    channel 3: -90 dBm
2024-09-03T18:06:12.548Z DRIVER   all queues idle
2024-09-03T18:06:23.582Z CNTRLR » [Node 004] pinging the node...
2024-09-03T18:06:23.591Z DRIVER   all queues busy
2024-09-03T18:06:23.609Z SERIAL » 0x010f00a90001000401002500000000a3db                                (17 bytes)
2024-09-03T18:06:23.630Z DRIVER » [Node 004] [REQ] [SendDataBridge]
                                  │ source node id:   1
                                  │ transmit options: 0x25
                                  │ callback id:      163
                                  └─[NoOperationCC]
2024-09-03T18:06:23.654Z SERIAL « [ACK]                                                                   (0x06)
2024-09-03T18:06:23.657Z SERIAL « 0x010401a90152                                                       (6 bytes)
2024-09-03T18:06:23.661Z SERIAL » [ACK]                                                                   (0x06)
2024-09-03T18:06:23.666Z DRIVER « [RES] [SendDataBridge]
                                    was sent: true
2024-09-03T18:06:34.618Z SERIAL « 0x011d00a9a301044c007f7f7f7f7f00010600000000420702047f7f7f7f7fe5    (31 bytes)
2024-09-03T18:06:34.622Z SERIAL » [ACK]                                                                   (0x06)
2024-09-03T18:06:34.631Z DRIVER « [REQ] [SendDataBridge]
                                    callback id:            163
                                    transmit status:        NoAck, took 11000 ms
                                    routing attempts:       7
                                    protocol & route speed: Z-Wave, 40 kbit/s
                                    routing scheme:         Resort to Direct
                                    TX channel no.:         1
                                    beam:                   1000 ms
                                    route failed here:      2 -> 4
2024-09-03T18:06:34.645Z CNTRLR   [Node 004] The node did not respond after 1 attempts, it is presumed dead
2024-09-03T18:06:34.653Z CNTRLR   [Node 004] ping failed: The node did not acknowledge the command (ZW0204)
2024-09-03T18:06:34.656Z CNTRLR   [Node 004] Cannot rebuild routes because the node is not responding.
2024-09-03T18:06:34.659Z DRIVER   all queues idle
2024-09-03T18:06:42.503Z DRIVER   all queues busy
2024-09-03T18:06:42.520Z SERIAL » 0x0103003bc7                                                         (5 bytes)
2024-09-03T18:06:42.522Z DRIVER » [REQ] [GetBackgroundRSSI]
2024-09-03T18:06:42.545Z SERIAL « [ACK]                                                                   (0x06)
2024-09-03T18:06:42.549Z SERIAL « 0x0107013ba6a5a5abcf                                                 (9 bytes)
2024-09-03T18:06:42.554Z SERIAL » [ACK]                                                                   (0x06)
2024-09-03T18:06:42.556Z DRIVER « [RES] [GetBackgroundRSSI]
                                    channel 0: -90 dBm
                                    channel 1: -91 dBm
                                    channel 2: -91 dBm
                                    channel 3: -85 dBm
2024-09-03T18:06:42.561Z DRIVER   all queues idle
2024-09-03T18:07:12.503Z DRIVER   all queues busy
2024-09-03T18:07:12.509Z SERIAL » 0x0103003bc7                                                         (5 bytes)
2024-09-03T18:07:12.511Z DRIVER » [REQ] [GetBackgroundRSSI]
2024-09-03T18:07:12.521Z SERIAL « [ACK]                                                                   (0x06)
2024-09-03T18:07:12.528Z SERIAL « 0x0107013ba3a0a0a6c7                                                 (9 bytes)
2024-09-03T18:07:12.536Z SERIAL » [ACK]                                                                   (0x06)
2024-09-03T18:07:12.538Z DRIVER « [RES] [GetBackgroundRSSI]
                                    channel 0: -93 dBm
                                    channel 1: -96 dBm
                                    channel 2: -96 dBm
                                    channel 3: -90 dBm
2024-09-03T18:07:12.544Z DRIVER   all queues idle
2024-09-03T18:07:42.504Z DRIVER   all queues busy
2024-09-03T18:07:42.512Z SERIAL » 0x0103003bc7                                                         (5 bytes)
2024-09-03T18:07:42.514Z DRIVER » [REQ] [GetBackgroundRSSI]
2024-09-03T18:07:42.551Z SERIAL « [ACK]                                                                   (0x06)
2024-09-03T18:07:42.557Z SERIAL « 0x0107013ba7a2a2a8cd                                                 (9 bytes)
2024-09-03T18:07:42.561Z SERIAL » [ACK]                                                                   (0x06)
2024-09-03T18:07:42.563Z DRIVER « [RES] [GetBackgroundRSSI]
                                    channel 0: -89 dBm
                                    channel 1: -94 dBm
                                    channel 2: -94 dBm
                                    channel 3: -88 dBm
2024-09-03T18:07:42.569Z DRIVER   all queues idle
```

I will work towards more house-powered nodes to get the signal there but in the meantime what is this log telling me? It is from right after attempting to rebuild the routes the in this devices page in HA.

**Comment by firstof9** [comment]
```
2024-09-03T18:06:34.645Z CNTRLR   [Node 004] The node did not respond after 1 attempts, it is presumed dead
2024-09-03T18:06:34.653Z CNTRLR   [Node 004] ping failed: The node did not acknowledge the command (ZW0204)
2024-09-03T18:06:34.656Z CNTRLR   [Node 004] Cannot rebuild routes because the node is not responding.
```

Your node isn't on the network there for no commands can be sent to it, you'll have to fix your mesh before HA/ZwaveJS can talk to the lock.

**Comment by Sammy-cmd** [comment]
Circling Back to report my locks are all set up and working. I had to move my NUC / Controller to a high location more central in my house and put in a wired repeater to help route around a massive masonry fireplace that goes from the floor to above the roof and is about 2 or more feet thick and the full width of the wall separating the Family Room from the Laundry Room to get the lock between the laundry room and garage to show up on the network.

Very pleased thus far with Keymaster and now I need to set up notifications so I know when certain people are coming through the locks and into my house.
