### ISSUE TITLE
ISSUE: HA OS update to 2024.9 and Badges

### ISSUE THREAD

**Issue by Sammy-cmd** [FutureTense/keymaster#383]
**Describe the bug**
HA OS update to 2024.9 has affected the badges for the Fake Sensors 

**Environment (please complete the following information):**

- OS: HA OS
- Type of system that HA is running on: NUC via Virtual Box
- Home Assistant version: 2024.9
- Hassio/Docker/Core? N/A
- Component version: 0.98
- Z-Wave integration name:  zwave_js
- Lock make and model: Kwikset HC 620

**Logs**
Not sure what log to post but will when directed to do so.

**Screenshots**
Please see post in the HA Forum here: https://community.home-assistant.io/t/keymaster-z-wave-lock-manager-and-scheduler/166419/3041?u=sammy2

**Additional context**
Started after update. Restart of HA does not repair it. Something in the coding for badges in the update has caused issues with these badges in Keymaster.

**Comment by firstof9** [comment]
Not a bug, remove the badges.

**Comment by Sammy-cmd** [comment]
I guess they don't do anything so I'll just remove them.
