### ISSUE TITLE
ISSUE: Missing script keymaster_<lockname>_manual_notify

### ISSUE THREAD

**Issue by ArunGupta2017** [FutureTense/keymaster#385]
Home Assistant showing the following error:

The automation "keymaster_kitchendoor User Notifications" (automation.keymaster_kitchendoor_user_notifications) has an unknown action: script.keymaster_kitchendoor_manual_notify.

This error prevents the automation from running correctly. Maybe this action is no longer available, or perhaps a typo caused it.

To fix this error, [edit the automation](/config/automation/edit/keymaster_kitchendoor User Notifications) and remove this action.

HassOS
Core 2024.9.3
Supervisor 2024.09.1
Operating System 13.1
Frontend 20240909.1

I have already run `keymaster: Generate lock manager files` and restarted HA but this error is still showing up under Settings -> System -> Repairs. There is no script by the name of keymaster_kitchendoor_manual_notify. This morning I made two changes to HA. Update HA core to 2024.9.3 and Z-Wave JS UI to 9.20.0.

**Comment by firstof9** [comment]
You are to make the script: https://github.com/FutureTense/keymaster/wiki/Notification-Example-Script#example-notification-script
