### ISSUE TITLE
ISSUE:Deprecation Log Error in Hass

### ISSUE THREAD

**Issue by coasttech** [FutureTense/keymaster#396]
I know nothing other than the message and to reach out to y'all. 

Logger: homeassistant.core
Source: helpers/deprecation.py:222
First occurred: 5:06:23 PM (1 occurrences)
Last logged: 5:06:23 PM

Config was used from keymaster, this is a deprecated alias which will be removed in HA Core 2025.11. Use homeassistant.core_config.Config instead, please report it to the author of the 'keymaster' custom integration

**Comment by firstof9** [comment]
#392 already fixed.
