### ISSUE TITLE
ISSUE: Wiki Documentation - numberbox-card is needed, not documented.

### ISSUE THREAD

**Issue by scyto** [FutureTense/keymaster#79]
**Describe the bug**
number box-card is also required to get this hacs integration working, wasn't listed in the wiki page where the other 3 are listed.

**Environment (please complete the following information):**

not sure this section is needed for a doc bug?

**Comment by raman325** [comment]
thanks, added! for future reference you can also update the Wiki page directly 😄

**Comment by scyto** [comment]
thanks, i couldn't find an edit control so i didn't; i have updated all sorts of wikis elsewhere on git hub, so more than willing to do that sort of stuff

you might want to check permissions :-) ?


![image](https://user-images.githubusercontent.com/11369180/107406224-0cbce000-6abd-11eb-9a72-8e17604c992c.png)

**Comment by raman325** [comment]
ah guess it's members only. Carry on then!

**Comment by scyto** [comment]
@raman325 well you can open it up to edits, or i can raise bugs where i think there is lack of clarity / e.g. where i got stumped and re-read more than once. :-)

for example after installing hacs and rebooting it isn't clear that one should go to the normal every day hass integrations menu - i was just doing my second fresh install like an idiot forgetting that's where it means to go.  It seems obvious when one rereads after, but not as a set of instructions. Happy to help.

**Comment by raman325** [comment]
For now feel free to keep opening issues, since this is not my repo I don't feel comfortable making the decision over who can contribute to the Wiki.

Re: your feedback, are you referring to the part where you actually install `keymaster`? I can add a reference to the HACS docs, I just don't want to duplicate info that is available elsewhere
