### ISSUE TITLE
ISSUE: Pin setting and synchronization will not work until a sever restart after adding any zwavejs integration based lock

### ISSUE THREAD

**Issue by scyto** [FutureTense/keymaster#80]
**Describe the bug**
~~I am unclear if the zwavejs support is intended to be used with just the new zwave js integration OR if it can be used with zwavejs2mqtt too?~~

~~I ask because on mine it is not retrieving the existing pin codes with a pin status of 'connecting'
Once clarified I can convert this to an actual feature bug / request as needed.~~

Pin setting and retrieval doesn't work with my lock via zwavejs/mqtt or zeavejs/new integration paths.

--edit--
i get same with both MQTT path and with new integration

--edit2-- i tried to set a pin, it didn't change pin or sync the pin - this seems to be case for both MQTT method and new integration methode

**Environment (please complete the following information):**

- Keymaster v0.0.16
- OS: HassOS
- hyper-v vm
- core-2021.2.2
- Home Assistant OS 5.11
- Hasssio
- zwavejs 6.1.3
- zwavejs2mqtt app 6.1.3

**Logs**
Paste your error logs here.

**Screenshots**

**Additional context**
Please add emails in plain/text format if possible and applicable.
![image](https://user-images.githubusercontent.com/11369180/107327359-e0c04100-6a61-11eb-879e-5f211bb48e49.png)

![image](https://user-images.githubusercontent.com/11369180/107327417-f33a7a80-6a61-11eb-8625-51be8848c48a.png)

**Comment by raman325** [comment]
did you set the PIN value before trying to enable the slot? In your screenshot the PIN shows as unknown so the service call would fail

**Comment by scyto** [comment]
yes the pin was already set years ago by another system (in the white screecap above you can see the values when one interrogates the device directly in the zwavejs2mqtt.

i tried setting a new pin in slot 4 via the keymaster UI (which is a slot that has never been used) that did nothing too.

or maybe you meant something else, this is my first time using keymaster so not sure what 'golden path to success' looks like?

**Comment by scyto** [comment]
this sounds in terms of 'end use symptoms' a lot  like https://github.com/FutureTense/keymaster/issues/33 ?

**Comment by raman325** [comment]
keymaster expects to be the one managing the PINs. It's "connecting" because the PIN on the slot (4567) doesn't match the PIN we expect (unknown). Your best bet is to re-enter the PIN into the input text and then flip it off and on, that should cause it to switch to Connected

**Comment by raman325** [comment]
can you confirm whether or not this was resolved @scyto ?

**Comment by scyto** [comment]
I only just resolved some underlying issues that may have been affecting this, will test this weekend.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by scyto** [comment]
Ok, sorry for the delay.

I am doing tail -f on zwavejs_1.log (at debug level)

I am seeing no attempted communication to the lock at all - so i assume the issue is between the keymaster integration and MQTT / zwavejs2mqtt?  (i am NOT using the new HA zwavejs integration).

I manually set code 1 and code to available instead of enabled via zwavejs2mqtt and that communication works.

Not sure where to go next with this?

**Comment by firstof9** [comment]
MQTT isn't the method we're supporting for communication, only `zwave`, `ozw`, and `zwavejs` integrations, as they expose services we utilize to set/get/clear user codes.

**Comment by scyto** [comment]
I just installed the zwavejs integration

that doesn't work either

**Comment by scyto** [comment]
yes it does - an extra reboot was needed as i installed the integration AFTER i had installed keymaster.
Keymaster let me create the locks, but for some reason a reboot was needed.

**Comment by scyto** [comment]
sorry, reopening.

This has worked perfectly for the first lock I added but not for locks 2,3 and 4.
Before adding any locks to keymaster i set all usercode slots back to available on all locks, with no codes.

Lock 1 shows the codes being in sync.
Lock 2,3 and show the codes not being in sync, but I was watching zwavejs logs and every lock got set to enabled and the code did get set correctly.
It seems only the notification back that allows keymaster to know if a lock is set is failing.

I seen nothing untoward in the logs.
Is there anything i can do to generate logs or do tests to idicate what the issue is?

I am on:

core-2021.2.3
wavejs Version 6.4.0
Zwavejs-server Version 1.0.0-beta.7

**---edit in realtime---
i tried a reboot again, and again it fixed it - seems a reboot is needed after adding the lock each time.
is that a bug?**

**Comment by raman325** [comment]
I can't explain the reboot. Are you having to reboot after you add the lock to your network, or to keymaster?

**Comment by scyto** [comment]
after i add to keymaster - it happened with the first lock and then was needed for the subsequent 3 i had to do later.

**Comment by raman325** [comment]
when you added the locks, did you get a notification saying that no restart was needed? I wonder if there's something we are missing during the reload

**Comment by scyto** [comment]
> when you added the locks, did you get a notification saying that no restart was needed? I wonder if there's something we are missing during the reload

yes it told me I didn't need to reboot as it managed to do everything (don't have exact wording to hand.
