### ISSUE TITLE
ISSUE: Sunday through Saturday switches resetting after reboot

### ISSUE THREAD

**Issue by jdc0730** [FutureTense/keymaster#87]
Describe the bug
If a particular day is disabled, it is re-enabled after a server restart. The codes are set correctly as the switch is set, so the codes are sent on previously disabled days on a restart.

Environment (please complete the following information):

OS: Docker
Type of device: Synology
Home Assistant version: 2021.2.3
Hassio/Docker/Core? Docker
Component version: 0.0.18
Logs
No errors in logs

**Comment by raman325** [comment]
I have a fix for this (see linked PR0. Will merge soon
