### ISSUE TITLE
No version 0.2 shown on github, but hacs....

### ISSUE THREAD

**Issue by topogio** [FutureTense/keymaster#89]
So Hacs is saying v0.0.2 is available, so I updated and it broke my keymaster and ozw .... I come here and see that the v0.0.19 is the current release...  I have not selected to receive any betas and there is no way to say I would or would not want betas to show like in the addon store of HA.  

Mentioning this as it made for a bit of frustration and maybe can save others the same headache.  

Love the way keymaster currently works and am looking to switch to zwave_js soon... :D

Thanks for all the hardwork you've put into this project, It is a great addon.

**Comment by raman325** [comment]
What version of Home Assistant are you running? If you are running the latest you should be able to update to the latest version, which you definitely should do because there were some issues in the early releases

**Comment by topogio** [comment]
I have the current version, but somehow it got botched and I reset my vm snapshot and then reupdated the home assistant core and hacs and voila, it is solved.... Thank you for the quick reply...
