### ISSUE TITLE
ISSUE: duplicate and incomplete code slots in lockname_lovelace when changing start number

### ISSUE THREAD

**Issue by scyto** [FutureTense/keymaster#90]
**Describe the bug**
duplicate code slots in lockname_lovelace caused by editing starting number for code

**Environment (please complete the following information):**

- OS:hassos
- Type of device: VM
- Home Assistant version: core-2021.2.3
- Component version: v0.0.19

**Logs**
no error logs 

**Screenshots**
no screen shots

**Additional context**
Repro:

- add integration with new lock, create 6 code slots starting at number 1
- check lockname_lovelace is correctly created
- edit the integration and change the the starting number to 3
- check the lockname_lovelace file - while the code slots do start at 3 they are duplicated so I have 2x code 3, 2x code4, 2x code5 and 2x code 6 - resulting in 8 code slots instead of 6 with right numbers

example attached

[frontdoor_bottom_lock_lovelace - Copy.txt](https://github.com/FutureTense/keymaster/files/6024317/frontdoor_bottom_lock_lovelace.-.Copy.txt)

**Comment by scyto** [comment]
i realize it didn't create any of the other artifacts needed for code 7 and 8, so this is about more than lovelace file

![image](https://user-images.githubusercontent.com/11369180/108754946-77c5d800-74fb-11eb-9b61-6260f40684d2.png)

**Comment by scyto** [comment]
these are the integration settings for the lock in question

![image](https://user-images.githubusercontent.com/11369180/108755097-a93ea380-74fb-11eb-8d45-4b440b4a757f.png)

**Comment by raman325** [comment]
@scyto as I mentioned on Discord, I believe this is resolved with the latest update. Can you try it and let me know?

**Comment by scyto** [comment]
fixed by https://github.com/FutureTense/keymaster/pull/93 - thanks @raman325
