### ISSUE TITLE
ISSUE: node_id error on ha restart

### ISSUE THREAD

**Issue by rchamp26** [FutureTense/keymaster#94]
I'm getting a node_id error on HA Restart

**Environment (please complete the following information):**

- Docker Supervised install
- HP EliteDesk 800 G2
- HA version: 2021.2.3
- Home Assistant version: [e.g. 0.105.5]
- Component version: 0.0.20 and same issue on 0.0.21
-  baked in Zwave integration (1.4) still

**Logs**
`Logger: custom_components.keymaster
Source: custom_components/keymaster/helpers.py:112
Integration: keymaster (documentation, issues)
First occurred: 3:20:59 PM (1 occurrences)
Last logged: 3:20:59 PM

Unexpected error fetching keymaster data: 'node_id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/keymaster/__init__.py", line 503, in async_update_usercodes
    return await self.hass.async_add_executor_job(self.update_usercodes)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/keymaster/__init__.py", line 584, in update_usercodes
    node_id = get_node_id(self.hass, self._lock.lock_entity_id)
  File "/config/custom_components/keymaster/helpers.py", line 112, in get_node_id
    return state.attributes[ATTR_NODE_ID]
KeyError: 'node_id'`

**Additional context**
keymaster still seems to work. perhaps this is an issue with keymaster trying to get the zwave node_id before zwave is started up.

**Comment by firstof9** [comment]
> perhaps this is an issue with keymaster trying to get the zwave node_id before zwave is started up

It seems likely.

**Comment by raman325** [comment]
Yes this is a known issue. The first couple of polls may fail but it will eventually silently stop and work as normal once HA is finished starting up. I have a PR open that will address this.

**Comment by raman325** [comment]
btw @rchamp26, I'm assuming you're the same person I'm talking to in the forums. Did you get a chance to test the bug fix for the custom branch? I'm mainly waiting on confirmation that the changes work with the original zwave integration before merging

**Comment by rchamp26** [comment]
Yes same person. I did test the experimental branch per our last coms but had the issue with the binary sensor getting created. If there is another update that addresses that I'll clear this out and test the experimental again. Once zwave comes up keymaster does work fine currently on 0.0.21 stable. I just get that initial error on start, which as you explain is expected

**Comment by raman325** [comment]
I added a new commit that **should** resolve the issue you found and reported. Please try again when you get a chance

**Comment by raman325** [comment]
@rchamp26 bumping this ^

**Comment by rchamp26** [comment]
Sorry missed that. Is the commit in the experimental branch or public branch?

**Comment by raman325** [comment]
no worries! its all in the experimental branch

**Comment by raman325** [comment]
@rchamp26 ^ sorry, not trying to rush you, just want to make sure you see this

**Comment by rchamp26** [comment]
@raman325 , sorry, i originally closed too soon, but i retested and your update seems to resolve my issue. just wanted to officially close the loop with comment

**Comment by raman325** [comment]
Sweet! Thanks for confirmation. That's a good thing too since I got impatient and released it anyway 😅
