### ISSUE TITLE
ISSUE: Slots stuck at 'connecting'

### ISSUE THREAD

**Issue by scyto** [FutureTense/keymaster#98]
Keymaster stays in connecting state when on zwavejs2mqqt (using ha integration in core-2021.2.3)
I also note if i try and enable a new code slot i see no corresponding zwave traffic
I tried latest HA beta that didn't work.
Haven't tried pulling ha integration from github.

App Version 1.4.0+a213b25.a213b25
Zwavejs Version 6.5.0-ec2d387
Zwavejs-server Version 1.0.

Is this a known issue?  
Ok if it is, i get what using daily builds means :-)

**Comment by firstof9** [comment]
Anything about keymaster in your Home Assistant log?

**Comment by scyto** [comment]
yes
```
2021-02-26 16:41:01 ERROR (MainThread) [custom_components.keymaster] Unexpected error fetching keymaster data: 'NoneType' object has no attribute 'values'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 149, in async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _async_update_data
return await self.update_method()
File "/config/custom_components/keymaster/__init__.py", line 503, in async_update_usercodes
return await self.hass.async_add_executor_job(self.update_usercodes)
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/keymaster/__init__.py", line 528, in update_usercodes
for slot in get_usercodes(node):
File "/usr/local/lib/python3.8/site-packages/zwave_js_server/util/lock.py", line 76, in get_usercodes
return _get_code_slots(node, True)
File "/usr/local/lib/python3.8/site-packages/zwave_js_server/util/lock.py", line 48, in _get_code_slots
value = get_code_slot_value(node, code_slot, LOCK_USERCODE_PROPERTY)
File "/usr/local/lib/python3.8/site-packages/zwave_js_server/util/lock.py", line 21, in get_code_slot_value
value = node.values.get(
AttributeError: 'NoneType' object has no attribute 'values'```

**Comment by raman325** [comment]
can you attach a state dump of your network and let me know which node is the lock?

**Comment by scyto** [comment]
user codes redacted
nodes 2,3,4,5

[zwave_js_dump.jsonl.txt](https://github.com/FutureTense/keymaster/files/6057849/zwave_js_dump.jsonl.txt)

today on 
App Version 2.0.0+c2e3e82.c2e3e82
Zwavejs Version 6.5.1-ee8d1f3
Zwavejs-server Version 1.1.0

and still on core-2021.2.3 (moving to b3 didn't help)

**Comment by raman325** [comment]
which node is the one facing the issue?

**Comment by firstof9** [comment]
I believe he posted nodes 2 3 4 and 5 are his locks.

**Comment by raman325** [comment]
I mean which one was the one that had the problem, but I think I know what's going on here. Will push a potential fix soon

**Comment by raman325** [comment]
I mean which one was the one that had the problem, but now I am seeing that shouldn't matter based on the error. @scyto did you delete the `zwave_js` integration and re set it up at some point without restarting HA? For some reason the references we grab during initial setup are stale. Wondering if we need to grab those references every time, or do something else to ensure that we have the right references.

**Comment by raman325** [comment]
put another way, if you were to reboot your HA instance, do you still face the same issue?

**Comment by scyto** [comment]
@raman325 no i did nothing to the configuration of keymaster, it is possible i remove the HA integration and re-added because the 'reload' option disappeared from it (but i have rebooted multiple times since then).

My assumption is that even through removal and readd that unique device ID's stay the same (they seem too).

**Comment by raman325** [comment]
The config entry ID changes everytime you delete and re-add the integration, as does the device registry ID and the node object. All of this gets re-captured when keymaster is reloaded, either through Reload or by restarting Home Assistant

**Comment by raman325** [comment]
Can you try disabling and re-enabling the PIN? Do you get the same error in the logs assuming it still doesn't work?

**Comment by raman325** [comment]
Also can you validate that your entity ID as stored in keymaster is still correct? You can do this by accessing the config entry options

**Comment by raman325** [comment]
try updating and see if that resolves your issue (you will need to regenerate package files). If it doesn't, then can you answer the above questions? Just trying to narrow this issue down

**Comment by scyto** [comment]
@raman325 you are right, looking at the options they were invalidated

For other zwave devices / entities via integration I don't recall seeing an issue like this so long as entity / device name doesn't change (which it doesn't)  for example my normal lock/unlock buttons still work.

![image](https://user-images.githubusercontent.com/11369180/109545539-d6500080-7a7d-11eb-9056-941b7baf1e89.png)

i can regnerate.

**Comment by raman325** [comment]
yeah so we rely heavily on the entity IDs in order to make this work for `zwave_js`. If they change, the keymaster config has to be updated, otherwise we have no way of accessing your lock.

Glad you were able to resolve the issue!

**Comment by scyto** [comment]
update for all, this looks like it was caused by a breaking change in how the zwavejs HA integration choose to name entities.
Previously it only used product name set in zwavejs.  Now it will use the friendly name set in zwavejs but not the area (which is annoying as now i have duplicate entity ids, oh well). this may  invalidate existing lock configs as it changes the underlying entity name.

**Comment by raman325** [comment]
I wouldn't call it a breaking change because you only see the name change if you delete the `zwave_js` integration and recreate it. Most people rename their entities to something more friendly, although to your point we could make it better by adding the area to the name (assuming this is possible).

**Comment by scyto** [comment]
For me this happened on upgrade I think, not deletion, but not definite on that.
